#include <time.h>
#include <math.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "soc/adc_channel.h"
#include "esp_adc/adc_oneshot.h"
#include "esp_adc/adc_cali.h"
#include "esp_event.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_http_client.h"
#include "esp_netif_sntp.h"
#include "esp_sleep.h"
#include "nvs_flash.h"
#include "cJSON.h"
#include "driver/gpio.h"
#include "driver/rtc_io.h"
#include "soc/rtc.h"
#include "ulp_riscv.h"
#include "display.h"
#include "fonts.h"
#include "icons.h"
#include "ulp_main.h" // Generated by CMake, extern declarations for ULP variables
#include "secret.h" // Not included in repo
/* ^ Defines:
 * - WIFI_SSID
 * - WIFI_PASSWORD
 * - LATITUDE
 * - LONGITUDE
 * - API_KEY
 */

/* Following functions are placed in IRAM as they are frequently called:
 * - spi_write_byte: called by all SPI write functions
 * - spi_write_command: called for every command sent to the display
 * - spi_write_data: called for every byte of data sent to the display
 * - frame_draw_byte: called by all frame drawing functions */

// TODO: use espidf heap tracing to check for memory leaks

/* Main event group */
static EventGroupHandle_t event_group = NULL;
#define WIFI_DONE_BIT BIT0
#define SNTP_DONE_BIT BIT1
#define WEATHER_DONE_BIT BIT2
#define ALL_DONE_BITS (WIFI_DONE_BIT | SNTP_DONE_BIT | WEATHER_DONE_BIT)

/* Error variables and definitions */
enum error_type
{
    WIFI_ERROR = 0,
    SNTP_ERROR,
    WEATHER_ERROR,
    EPD_ERROR,
    MEMORY_ERROR,
    OTHER_ERROR,
    ASSERT, // Used in place of assert() to allow for displaying error on display
    NO_ERROR
};
static RTC_FAST_ATTR enum error_type current_error = NO_ERROR; // RTC_FAST_ATTR persists deep sleep
static RTC_FAST_ATTR uint8_t error_count[NO_ERROR] = {0}; // Indexed by error_type enum
static uint64_t deferred_uS = 0;
#define MAX_ERROR_COUNT 10
#define STRINGIFY(x) #x // Used for converting macro values to strings for logging

/* Wall clock time */
static time_t now;
static struct tm timeinfo;
#define UPDATE_TIME do { time(&now); localtime_r(&now, &timeinfo); } while(0)

/* Wifi definitions and variables */
static EventGroupHandle_t wifi_event_group;
static int retry_num = 0;
static esp_netif_t *wifi_if = NULL;
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1
#define MAX_RETRY_NUM      5

/* Battery definitions and variables */
static uint8_t battery_percentage = 0;
#define BATTERY_THRESHOLD 10 // Percentage at which the battery is considered critically low

/* Root server certificate for api.openweathermap.org embedded by CMake */
extern const uint8_t server_cert_pem_start[] asm("_binary_openweather_pem_start");
extern const uint8_t server_cert_pem_end[]   asm("_binary_openweather_pem_end");

/* ULP binary embedded by CMake */
extern const uint8_t bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t bin_end[]   asm("_binary_ulp_main_bin_end");

/* Weather id definitions */
enum
{
    THUNDERSTORM_START = 200,
    THUNDERSTORM_END   = 232,
    DRIZZLE_START      = 300,
    DRIZZLE_END        = 321,
    RAIN_START         = 500,
    RAIN_END           = 531,
    SNOW_START         = 600,
    SNOW_END           = 622,
    ATMOSPHERE_START   = 701,
    ATMOSPHERE_END     = 781,
    CLEAR_SKY          = 800,
    CLOUDS_START       = 801,
    CLOUDS_END         = 804
};

static RTC_FAST_ATTR struct weather_today
{
    uint16_t id;
    char description[32];
    float current_temp;
    float feels_like_temp;
    float high_temp;
    float low_temp;
    float wind_speed;
    uint16_t wind_direction_degrees; // Degrees from north that the wind is coming from
    float cloudiness; // % of sky covered by clouds
} weather;

#define FORECAST_HOURS 12
static RTC_FAST_ATTR struct hourly_forecast
{
    float temp;
    float precipitation_chance;
    char time[6]; // "%Ip" Datetime string
} hourly_forecast[FORECAST_HOURS];

#define FORECAST_DAYS 8 // First item is current day, next 7 are forecast for next 7 days
static RTC_FAST_ATTR struct weather_forecast
{
    uint16_t id;
    float high_temp;
    float low_temp;
    float precipitation_chance;
    char day[10]; // "%A" Datetime string
} forecast[FORECAST_DAYS];

static uint8_t frame[EPD_HEIGHT][EPD_BYTE_WIDTH];

// TODO: Switch to hardware version of spi
static void IRAM_ATTR spi_write_byte(uint8_t byte)
{
    for (int i = 0; i < BITS_PER_BYTE; i++)
    {
        rtc_gpio_set_level(MOSI_PIN, (byte & 0x80) ? HIGH : LOW); // 0x80 = 10000000 BITMASK
        byte <<= 1;
        rtc_gpio_set_level(SCK_PIN, HIGH);
        rtc_gpio_set_level(SCK_PIN, LOW);
    }
}

static void IRAM_ATTR spi_write_command(uint8_t command)
{
    rtc_gpio_set_level(DC_PIN, LOW); // Command mode
    rtc_gpio_set_level(CS_PIN, LOW);
    spi_write_byte(command);
    rtc_gpio_set_level(CS_PIN, HIGH);
}

static void IRAM_ATTR spi_write_data(uint8_t data)
{
    rtc_gpio_set_level(DC_PIN, HIGH); // Data mode
    rtc_gpio_set_level(CS_PIN, LOW);
    spi_write_byte(data);
    rtc_gpio_set_level(CS_PIN, HIGH);
}

static void epd_reset()
{
    rtc_gpio_set_level(RST_PIN, HIGH);
    vTaskDelay(20 / portTICK_PERIOD_MS);
    rtc_gpio_set_level(RST_PIN, LOW); // Low is active
    vTaskDelay(20 / portTICK_PERIOD_MS);
    rtc_gpio_set_level(RST_PIN, HIGH);
}

static void epd_wait_until_idle()
{
    while (rtc_gpio_get_level(BUSY_PIN) == LOW)
    {
        ESP_LOGI("epd", "Display is busy...");
        vTaskDelay(10 / portTICK_PERIOD_MS);
    }
    ESP_LOGI("epd", "Display is released");
}

static void epd_init()
{
    /* Datasheet at https://files.waveshare.com/upload/6/60/7.5inch_e-Paper_V2_Specification.pdf
     * was used as a reference for the initialization sequence and commands */
    epd_reset();

    /* Default from datasheet unless otherwise specified */
    spi_write_command(BOOSTER_SOFT_START);
    spi_write_data(0x17);
    spi_write_data(0x17);
    spi_write_data(0x27);
    spi_write_data(0x17);

    spi_write_command(POWER_SETTING);
    spi_write_data(0x07);
    spi_write_data(0x17);
    spi_write_data(0x3f);
    spi_write_data(0x3f);

    spi_write_command(POWER_ON);
    epd_wait_until_idle();

    spi_write_command(PANEL_SETTING);
    spi_write_data(0x1f);

    spi_write_command(RESOLUTION_SETTING);
    spi_write_data(0x03);
    spi_write_data(0x20);
    spi_write_data(0x01);
    spi_write_data(0xe0);

    spi_write_command(DUAL_SPI);
    spi_write_data(0x00);

    spi_write_command(TCON_SETTING);
    spi_write_data(0x22);

    /* Altered from default to transfer data from NEW to OLD automatically */
    spi_write_command(VCOM_DATA_INTERVAL);
    spi_write_data(0x18);
    spi_write_data(0x07);

    /* Enable fast refresh */
    spi_write_command(CASCADE_SETTING);
    spi_write_data(0x02);
    spi_write_command(FORCE_TEMPERATURE);
    spi_write_data(0x5a);

    ESP_LOGI("epd", "Initialization complete");
}

static void epd_clear()
{
    epd_wait_until_idle();
    spi_write_command(TRANSFER_DATA_2);
    for (size_t i = 0; i < (EPD_HEIGHT * EPD_BYTE_WIDTH); i++)
    {
        spi_write_data(0x00);
    }
    spi_write_command(DISPLAY_REFRESH);
    epd_wait_until_idle();
}

static void epd_write_frame()
{
    epd_wait_until_idle();
    spi_write_command(TRANSFER_DATA_2);
    rtc_gpio_set_level(CS_PIN, HIGH);
    for (size_t i = 0; i < EPD_HEIGHT; i++)
    {
        for (size_t j = 0; j < EPD_BYTE_WIDTH; j++)
        {
            spi_write_data(frame[i][j]);
        }
    }
    spi_write_command(DISPLAY_REFRESH);
    epd_wait_until_idle();
}

static void epd_sleep()
{
    spi_write_command(POWER_OFF);
    epd_wait_until_idle();
}

static void IRAM_ATTR frame_draw_byte(int x, int y, uint8_t byte)
{
    if (unlikely(x < 0 || x >= EPD_WIDTH || y < 0 || y >= EPD_HEIGHT))
    {
        ESP_LOGE("frame", "Byte position out of bounds: x=%d, y=%d", x, y);
        return;
    }
    /* Shift the byte to align with the correct bits in the frame buffer, then OR it with the existing byte
     * to preserve any pixels that have already been drawn in that byte. */
    frame[y][x / BITS_PER_BYTE] |= byte >> (x % BITS_PER_BYTE);
    /* If the byte being drawn isn't aligned to a byte boundary, then
     * the byte next to it also needs to be updated with the remaining bits. */
    if ((x % BITS_PER_BYTE) != 0 && (x / BITS_PER_BYTE + 1) < EPD_BYTE_WIDTH)
    {
        frame[y][x / BITS_PER_BYTE + 1] |= byte << (BITS_PER_BYTE - (x % BITS_PER_BYTE));
    }
}

static void frame_draw_char(int x, int y, font_t font, char c)
{
    const uint8_t bytes_per_char = (font.width / BITS_PER_BYTE) + (font.width % BITS_PER_BYTE != 0);

    /* Subtract the first character in the font from the character to get the index,
     * then multiply by the number of bytes per character to get the offset in the font data array */
    const size_t offset = (c - ' ') * font.height * bytes_per_char;
    const uint8_t *char_start = font.table + offset;

    for (int i = 0; i < font.height; i++)
    {
        for (int j = 0; j < bytes_per_char; j++)
        {
            frame_draw_byte((x + (j * BITS_PER_BYTE)), (y + i), char_start[i * bytes_per_char + j]);
        }
    }
}

static void frame_draw_rotated_char(int x, int y, font_t font, char c)
{
    const uint8_t bytes_per_char = (font.width / BITS_PER_BYTE) + (font.width % BITS_PER_BYTE != 0);
    const size_t offset = (c - ' ') * font.height * bytes_per_char;
    const uint8_t *char_start = font.table + offset;
    const uint8_t bytes_per_row_rot = (font.height / BITS_PER_BYTE) + (font.height % BITS_PER_BYTE != 0);

    for (int i = 0; i < font.width; i++)
    {
        for (int j = 0; j < bytes_per_row_rot; j++)
        {
            uint8_t rotated_byte = 0;
            for (int k = 0; k < BITS_PER_BYTE; k++)
            {
                int new_col = (j * BITS_PER_BYTE) + k,
                    old_row = (font.height - 1) - new_col,
                    old_col = i;
                if (new_col >= font.height) { break; }

                const uint8_t src_byte = char_start[old_row * bytes_per_char + old_col / BITS_PER_BYTE];
                const uint8_t bit = (src_byte >> (BITS_PER_BYTE - 1 - (old_col % BITS_PER_BYTE))) & 1u;
                rotated_byte |= bit << (BITS_PER_BYTE - 1 - k);
            }
            frame_draw_byte((x + (j * BITS_PER_BYTE)), (y + i), rotated_byte);
        }
    }
}

static void frame_draw_giant_char(int x, int y, uint32_t offset)
{
    const uint8_t bytes_per_char = (font60.width / BITS_PER_BYTE) + (font60.width % BITS_PER_BYTE != 0);
    const uint8_t *char_start = font60.table + offset;

    for (int i = 0; i < font60.height; i++)
    {
        for (int j = 0; j < bytes_per_char; j++)
        {
            frame_draw_byte((x + (j * BITS_PER_BYTE)), (y + i), char_start[i * bytes_per_char + j]);
        }
    }
}

static void frame_draw_rotated_string(int x, int y, font_t font, const char *str)
{
    while (str[0] != '\0')
    {
        /* Slightly cursed code to make periods look better */
        y -= (str[0] == '.' && font.width < 20) ? ((font.width / 2) - 1) : 0;
        frame_draw_rotated_char(x, y, font, *str);
        y += (str[0] != '.') ? font.width : ((font.width / 2) + 2);
        str++;
    }
}

static void frame_draw_string(int x, int y, font_t font, const char *str)
{
    while (str[0] != '\0')
    {
        /* Slightly cursed code to make periods look better */
        x -= (str[0] == '.' && font.width < 20) ? ((font.width / 2) - 1) : 0;
        frame_draw_char(x, y, font, *str);
        x += (str[0] != '.') ? font.width : ((font.width / 2) + 2);
        str++;
    }
}

static void frame_draw_image(int x, int y, icon_t icon)
{
    for (int i = 0; i < icon.height; i++)
    {
        for (int j = 0; j < (icon.width / BITS_PER_BYTE); j++)
        {
            uint8_t byte = icon.data[i * (icon.width / BITS_PER_BYTE) + j];
            frame_draw_byte(x + (j * BITS_PER_BYTE), y + i, byte);
        }
    }
}

/* Used to draw degree symbol, unecessary, but I wanted to implement the midpoint circle algorithm */
static void frame_draw_circle(int center_x, int center_y, int radius)
{
    int x = radius,
        y = 0,
        decision_over_2 = 1 - x; // Decision criterion divided by 2 evaluated at x=r, y=0

    while (y <= x)
    {
        frame_draw_byte(center_x + x, center_y + y, 0xc0);
        frame_draw_byte(center_x + y, center_y + x, 0xc0);
        frame_draw_byte(center_x - x, center_y + y, 0xc0);
        frame_draw_byte(center_x - y, center_y + x, 0xc0);
        frame_draw_byte(center_x - x, center_y - y, 0xc0);
        frame_draw_byte(center_x - y, center_y - x, 0xc0);
        frame_draw_byte(center_x + x, center_y - y, 0xc0);
        frame_draw_byte(center_x + y, center_y - x, 0xc0);
        y++;
        if (decision_over_2 <= 0) { decision_over_2 += 2 * y + 1; }
        else                      { x--; decision_over_2 += 2 * (y - x) + 1; }
    }
}

static void frame_draw_line(int x0, int y0, int x1, int y1, int thickness)
{
    int dx  = abs(x1 - x0),
        sx  = x0 < x1 ? 1 : -1,
        dy  = -abs(y1 - y0),
        sy  = y0 < y1 ? 1 : -1,
        err = dx + dy,
        e2;
    bool straight_line = (dx == 0 || dy == 0);

    /* For straight lines simply iterate over x/y to draw them */
    if (straight_line)
    {
        if (dy == 0)
        {
            if (thickness == 1)
            {
                while (x0 != x1)
                {
                    frame_draw_byte(x0, y0, 0x80);
                    x0 += sx;
                }
            } else {
                for (int i = 0; i < thickness; i++)
                {
                    /* Recursively draw lines on either side of the original line to create thickness,
                     * alternating sides to keep it centered */
                    int8_t flip = (i % 2 == 0) ? ((i / 2) * - 1) : ((i + 1) / 2);
                    frame_draw_line(x0, y0 + flip, x1, y1 + flip, 1);
                }
            }
        } else {
            while (y0 != y1)
            {
                uint8_t byte = (uint8_t)(0xFF00 >> thickness);
                frame_draw_byte(x0, y0, byte);
                y0 += sy;
            }
        }
    }
    else if (thickness > 1)
    {
        for (int i = 0; i < thickness; i++)
        {
            int8_t flip = (i % 2 == 0) ? ((i / 2) * - 1) : ((i + 1) / 2);
            frame_draw_line(x0, y0 + flip, x1, y1 + flip, 1);
        }

    } else {
        /* Bresenham Line Drawing Algorithm for non straight lines */
        while (true)
        {
            frame_draw_byte(x0, y0, 0xc0);
            if (x0 == x1 && y0 == y1) break;
            e2 = 2 * err;
            if (e2 >= dy)
            {
                err += dy;
                x0 += sx;
            }
            if (e2 <= dx)
            {
                err += dx;
                y0 += sy;
            }
        }
    }
}

/* Draws a rectangle with vertical lines */
static void frame_draw_dotted_rectangle(int left, int top, int right, int bottom, int thickness)
{
    frame_draw_line(left, top, left, bottom, thickness);
    frame_draw_line(right, top, right, bottom, thickness);
    frame_draw_line(left, top, right, top, thickness);
    frame_draw_line(left, bottom, right, bottom, thickness);
    for (int i = left; i < right; i += 3)
    {
        frame_draw_line(i, top, i, bottom, thickness);
    }
}

static void frame_draw_filled_triangle(int x0, int y0, int x1, int y1, int x2, int y2)
{
    /* Sort the vertices by y-coordinate ascending (y0 <= y1 <= y2) */
    if (y0 > y1) { int t=x0; x0=x1; x1=t; t=y0; y0=y1; y1=t; }
    if (y0 > y2) { int t=x0; x0=x2; x2=t; t=y0; y0=y2; y2=t; }
    if (y1 > y2) { int t=x1; x1=x2; x2=t; t=y1; y1=y2; y2=t; }
    int total_h = y2 - y0;

    /* Scanline algorithm */
    for (int y = y0; y <= y2; y++)
    {
        double xa = (x0 + (double)(x2 - x0) * (y - y0) / total_h),
               xb;
        if (y <= y1)
        {
            int seg = y1 - y0;
            xb = (seg == 0) ? x0 : (x0 + (double)(x1 - x0) * (y - y0) / seg);
        } else {
            int seg = y2 - y1;
            xb = (seg == 0) ? x1 : (x1 + (double)(x2 - x1) * (y - y1) / seg);
        }
        if (xa > xb) { double tmp = xa; xa = xb; xb = tmp; }
        int ixa = (int)ceil(xa),
            ixb = (int)floor(xb),
            remaining = ixb - ixa + 1,
            x = ixa;
        while (remaining > 0)
        {
            int bits = (remaining > 8) ? 8 : remaining;
            uint8_t mask = (uint8_t)(0xFF00u >> bits);
            frame_draw_byte(x, y, mask);
            x += bits;
            remaining -= bits;
        }
    }
}

static void frame_draw_arrow(int x, int y, uint16_t degrees, int length)
{
    /* Convert degrees to radians and adjust so 0 degrees is pointing up */
    float radians = degrees * (M_PI / 180.0f);
    /* Screen space unit vector in the direction of the wind */
    double dx      = sin(radians),
           dy      = -cos(radians),
    /* Perpendicular vector for the arrowhead */
           px      = dy,
           py      = -dx,
    /* Coordinates where the arrowhead is attached to the line */
           base_cx = x + 0.50 * length * dx,
           base_cy = y + 0.50 * length * dy;
    /* Second set of coordinates for the line of the arrow */
    int    edge_x  = (int)(x + length * dx),
           edge_y  = (int)(y + length * dy),
    /* Coordinates for the tip of the arrow */
           tip_x   = (int)(x + 1 * length * dx),
           tip_y   = (int)(y + 1 * length * dy),
    /* Coordinates for two sides of the triangle for the arrowhead, using the perpendicular vector */
           b1x     = (int)round(base_cx + 0.30 * length * px),
           b1y     = (int)round(base_cy + 0.30 * length * py),
           b2x     = (int)round(base_cx - 0.30 * length * px),
           b2y     = (int)round(base_cy - 0.30 * length * py);
    frame_draw_line(x, y, edge_x, edge_y, 2);
    frame_draw_filled_triangle(tip_x, tip_y, b1x, b1y, b2x, b2y);
}

static void frame_draw_compass(int x, int y, uint16_t degrees, int length)
{
    /* Draw a circle for the compass background */
    frame_draw_circle(x, y, length);
    /* Draw arrow in the direction of the wind */
    frame_draw_arrow(x, y, degrees, length);
    /* Draw N, E, S, W indicators */
    frame_draw_char(x - (font16.width / 2), y - length - font16.height, font16, 'N');
    frame_draw_char(x + length + 4, y - (font16.height / 2), font16, 'E');
    frame_draw_char(x - (font16.width / 2) + 2, y + length + 2, font16, 'S');
    frame_draw_char(x - length - font16.width - 2, y - (font16.height / 2), font16, 'W');
}

static void frame_draw_time(int x, int y)
{
    UPDATE_TIME;
    uint16_t hour = ((timeinfo.tm_hour % 12) == 0) ? 12 : (timeinfo.tm_hour % 12),
             minute = timeinfo.tm_min,
             afternoon = (timeinfo.tm_hour >= 12) ? 0 : 1;
    ESP_LOGI("time", "Current time: %02d:%02d %s", (hour == 0) ? 12 : hour, minute, afternoon ? "AM" : "PM");

    uint8_t time[] =
    {
        (hour / 10) % 10,
        hour % 10,
        10, // ':' character
        (minute / 10) % 10,
        minute % 10,
        afternoon ? 11 : 12,
        13 // 'M' character
    };

    for (int i = 0; i < sizeof(time); i++)
    {
        switch (time[i])
        {
            case 0:  frame_draw_giant_char(x + (i * font60.width), y, ZERO); break;
            case 1:  frame_draw_giant_char(x + (i * font60.width), y, ONE); break;
            case 2:  frame_draw_giant_char(x + (i * font60.width), y, TWO); break;
            case 3:  frame_draw_giant_char(x + (i * font60.width), y, THREE); break;
            case 4:  frame_draw_giant_char(x + (i * font60.width), y, FOUR); break;
            case 5:  frame_draw_giant_char(x + (i * font60.width), y, FIVE); break;
            case 6:  frame_draw_giant_char(x + (i * font60.width), y, SIX); break;
            case 7:  frame_draw_giant_char(x + (i * font60.width), y, SEVEN); break;
            case 8:  frame_draw_giant_char(x + (i * font60.width), y, EIGHT); break;
            case 9:  frame_draw_giant_char(x + (i * font60.width), y, NINE); break;
            case 10: frame_draw_giant_char(x + (i * font60.width), y, COLON); break;
            case 11: frame_draw_giant_char(x + (i * font60.width), y, LETTER_A); break;
            case 12: frame_draw_giant_char(x + (i * font60.width), y, LETTER_P); break;
            case 13: frame_draw_giant_char(x + (i * font60.width), y, LETTER_M); break;
        }
    }
}

static void frame_draw_icon(int x, int y, uint16_t weather_id, bool small_image)
{
    UPDATE_TIME;
    bool is_daytime = (timeinfo.tm_hour >= 6 && timeinfo.tm_hour < 18);
    icon_t icon;

    /* Weather condition codes documented at https://openweathermap.org/weather-conditions */
    switch (weather_id)
    {
        case THUNDERSTORM_START ... THUNDERSTORM_END:
            icon = small_image ? thunder_small : thunder; break;
        case DRIZZLE_START ... DRIZZLE_END:
            icon = small_image ? drizzle_small : drizzle; break;
        case RAIN_START ... RAIN_END:
            icon = small_image ? rain_small : rain; break;
        case SNOW_START ... SNOW_END:
            icon = small_image ? snow_small : snow; break;
        case ATMOSPHERE_START ... ATMOSPHERE_END:
            icon = small_image ? haze_small : haze; break;
        case CLEAR_SKY:
            icon = (small_image) ? sun_small : ((is_daytime) ? sun : moon); break;
        case CLOUDS_START ... CLOUDS_END:
            icon = small_image ? cloud_small : cloud; break;
        default:
            ESP_LOGE("icon", "Unknown weather id: %d, using default cloud icon", weather_id);
            icon = small_image ? cloud_small : cloud; break;
    }
    frame_draw_image(x, y, icon);
}

/* Draw graph of two sets of points with the same y-axes, used for the temperature and precipitation forecast graph
 * first series of points is drawn with a solid line and the second series is drawn with as dashed boxes */
static void frame_draw_graph(int left, int top, int right, int bottom, float min_value, float max_value,
        struct hourly_forecast hourly_forecast[], int num_points, int num_lines_y, const char *left_label_format,
        const char *right_label_format)
{
    /* |_| shaped graph */
    frame_draw_line(left, top, left, bottom + 1, 2);
    frame_draw_line(left, bottom, right, bottom, 2);
    frame_draw_line(right, top, right, bottom + 2, 2);

    /* Y axis increases as you go down the screen */
    int    graph_width       = abs(right - left),
           graph_height      = abs(bottom - top),
           x_space           = graph_width / (num_points - 1),
           x_error           = graph_width - (x_space * (num_points - 1)),
           y_spacing         = graph_height / num_lines_y;
    double conversion_factor = graph_height / (max_value - min_value);

    for (int i = 0; i < num_points; i++)
    {
        int x = (i < (num_points - 1)) ? (x_space * i) + left : (x_space * i) + x_error + left;
        frame_draw_line(x, bottom, x, top, 1);
        /* Draw x-axis time labels rotated otherwise they overlap with each other */
        frame_draw_rotated_string(x - 8, bottom + 8, font12, hourly_forecast[i].time);
    }

    for (int i = 0; i <= num_lines_y; i++)
    {
        float label_value = min_value + ((max_value - min_value) / num_lines_y) * i;
        int y = bottom - (i * y_spacing);
        char label[16];

        frame_draw_line(left, y, right, y, 1);

        snprintf(label, sizeof(label), left_label_format, label_value);
        frame_draw_string(left - (font12.width * strlen(label)) - 14, y - 6, font12, label);
        frame_draw_circle(left - 12, y - 8, 2);

        snprintf(label, sizeof(label), right_label_format, label_value);
        frame_draw_string(right + 4, y - 6, font12, label);
    }

    for (int i = 1; i < num_points; i++)
    {
        int temp_y      = (int)bottom - round((hourly_forecast[i].temp - min_value) * conversion_factor),
            temp_y_prev = (int)(bottom - round((hourly_forecast[i - 1].temp - min_value) * conversion_factor)),
            precip_y    =
                (int)(bottom - round((hourly_forecast[i].precipitation_chance - min_value) * conversion_factor)),
            x           = (i < (num_points - 1)) ? (x_space * i) + left : (x_space * i) + x_error + left,
            x_prev      = (x_space * (i - 1)) + left;

        frame_draw_line(x_prev, temp_y_prev, x, temp_y, 3);

        if (precip_y < bottom)
        {
            frame_draw_dotted_rectangle(x_prev, precip_y, x, bottom, 1);
        }
    }
}

static char *float_to_string(float value)
{
    static char buffer[16];
    if ((int)value == value)
    {
        snprintf(buffer, sizeof(buffer), "%d", (int)value); // Trim trailing .0 for whole numbers
    } else {
        snprintf(buffer, sizeof(buffer), "%.1f", value);
    }
    return buffer;
}

static uint16_t float_str_width(float value, uint16_t font_width)
{
    char *str = float_to_string(value);
    uint16_t str_width = strlen(str) * font_width;
    if (font_width <= 22)
    {
        str_width -= (strchr(str, '.') != NULL) ? font_width : 0;
    } else {
        str_width -= (strchr(str, '.') != NULL) ? (font_width * 0.35) : 0;
    }
    return str_width;
}

static void frame_draw_forecast(int x, int y, struct weather_forecast forecast)
{
    frame_draw_string(x, y, font24, forecast.day);
    frame_draw_icon(x, y + 30, forecast.id, true);
    frame_draw_arrow(x + 60, y + 45, 0, 15);
    frame_draw_string(x + 70, y + 30, font16, float_to_string(forecast.high_temp));
    frame_draw_circle((x + 72 + float_str_width(forecast.high_temp, font16.width)), y + 25, 2);
    frame_draw_arrow(x + 60, y + 45, 179, 15);
    frame_draw_string(x + 70, y + 50, font16, float_to_string(forecast.low_temp));
    frame_draw_circle((x + 72 + float_str_width(forecast.low_temp, font16.width)), y + 45, 2);
    if (forecast.precipitation_chance > 0)
    {
        frame_draw_image(x + 42, y + 70, raindrop);
        frame_draw_string(x + 68, y + 70, font16, float_to_string(forecast.precipitation_chance));
        frame_draw_string(x + 68 + float_str_width(forecast.precipitation_chance, font16.width), y + 70,
                font12, "%");
    }
}

static void frame_draw_battery(int left, int top, int right, int bottom, uint8_t percentage)
{
    int tail_width = (right - left) / 10,
        tail_height = (bottom - top) / 3,
        body_width = (right - left) - tail_width,
        body_height = bottom - top,
        fill_point = (int)((percentage / 100.0f) * body_width);
    /* Draw battery body */
    frame_draw_line(left, top, left, bottom, 2);
    frame_draw_line(left, top, left + body_width, top, 2);
    frame_draw_line(left + body_width, top, left + body_width, bottom, 2);
    frame_draw_line(left, bottom, left + body_width + 2, bottom, 2);
    /* Draw battery tail */
    frame_draw_line(right - tail_width, top + tail_height, right, top + tail_height, 2);
    frame_draw_line(right - tail_width,
            top + tail_height + tail_height, right + 2, top + tail_height + tail_height, 2);
    frame_draw_line(right, top + tail_height, right, top + tail_height + tail_height, 2);
    /* Draw battery level */
    for (int i = top; i < bottom; i++)
    {
        frame_draw_line(left, i, left + fill_point, i, 1);
    }
    frame_draw_string(right + 4, top + 2, font12, float_to_string(percentage));
     frame_draw_string(right + 4 + float_str_width(percentage, font12.width), top + 2, font12, "%");
}

static void frame_draw_default()
{
    /* Quadrant 1: Current time and date */
    UPDATE_TIME;
    char timeinfo_str[64];
    frame_draw_string(450, 20, font24, "It is ");
    strftime(timeinfo_str, sizeof(timeinfo_str), "%A,", &timeinfo);
    frame_draw_string(450 + (font24.width * strlen("It is ")), 20, font24, timeinfo_str);
    strftime(timeinfo_str, sizeof(timeinfo_str), "%B %d, %Y", &timeinfo);
    frame_draw_string(470, 50, font24, timeinfo_str);
    frame_draw_time(CLOCK_X, CLOCK_Y);
    frame_draw_battery(730, 5, 770, 20, battery_percentage);

    /* Quadrant 2: Current weather conditions */
    frame_draw_icon(20, 20, weather.id, false);
    frame_draw_string(10, 130, font20, "Currently, ");
    frame_draw_string(30, 160, font40, float_to_string(weather.current_temp));
    frame_draw_circle(30 + float_str_width(weather.current_temp, font40.width), 165, 5);
    frame_draw_string(140, 180, font20, "feels like");
    frame_draw_string(290, 176, font24, float_to_string(weather.feels_like_temp));
    frame_draw_circle((292 + float_str_width(weather.feels_like_temp, font24.width)), 176, 3);
    frame_draw_string(175, 20, font24, "High");
    frame_draw_arrow(185 + (4 * font24.width), 40, 0, 20);
    frame_draw_string(260, 20, font24, float_to_string(weather.high_temp));
    frame_draw_circle((262 + float_str_width(weather.high_temp, font24.width)), 20, 3);
    frame_draw_string(175, 50, font24, " Low");
    frame_draw_arrow(185 + (4 * font24.width), 50, 179, 20);
    frame_draw_string(260, 50, font24, float_to_string(weather.low_temp));
    frame_draw_circle((262 + float_str_width(weather.low_temp, font24.width)), 50, 3);
    frame_draw_string(175, 80, font16, "Wind");
    frame_draw_string(175, 95, font16, "Speed");
    frame_draw_image(235, 75, wind);
    frame_draw_string(285, 85, font24, float_to_string(weather.wind_speed));
    frame_draw_string((288 + float_str_width(weather.wind_speed, font24.width)), 90, font12, "mph");
    frame_draw_compass(400, 100, weather.wind_direction_degrees, 15);
    frame_draw_string(175, 125, font16, "Cloud");
    frame_draw_string(175, 140, font16, "Cover");
    frame_draw_image(240, 120, cloud_small);
    frame_draw_string(295, 130, font24, float_to_string(weather.cloudiness));
    frame_draw_string(295 + float_str_width(weather.cloudiness, font24.width), 125, font20, "%");

    /* Quadrant 3: Graph showing temperature and precipitaion chance */
    frame_draw_graph(42, 240, 384, 430, 0, 100, hourly_forecast, FORECAST_HOURS, 10, "%.0fF", "%.0f%%");

    /* Quadrant 4: Forecast for next few days */
    frame_draw_forecast(445, 235, forecast[1]);
    frame_draw_forecast(565, 235, forecast[2]);
    frame_draw_forecast(685, 235, forecast[3]);
    frame_draw_forecast(445, 360, forecast[4]);
    frame_draw_forecast(565, 360, forecast[5]);
    frame_draw_forecast(685, 360, forecast[6]);
}

static void error_draw_message(const char *message)
{
    /* Clear the frame */
    memset(frame, 0x00, sizeof(frame));
    /* Draw error message in the middle of the screen */
    int x = (EPD_WIDTH - (strlen(message) * font40.width)) / 2;
    int y = (EPD_HEIGHT - font40.height) / 2;
    frame_draw_string(x, y, font40, message);
    epd_init();
    epd_write_frame();
    epd_sleep();
}

static void error_handler(enum error_type type, const char *message)
{
    switch (type)
    {
        case WIFI_ERROR:
            ESP_LOGE("wifi", "%s", message); break;
        case SNTP_ERROR:
            ESP_LOGE("sntp", "%s", message); break;
        case WEATHER_ERROR:
            ESP_LOGE("weather", "%s", message); break;
        case EPD_ERROR:
            ESP_LOGE("epd", "%s", message); break;
        case MEMORY_ERROR:
            ESP_LOGE("memory", "%s", message); break;
        case OTHER_ERROR:
            ESP_LOGE("error", "%s", message); break;
        case ASSERT:
            ESP_LOGE("assert", "%s", message); break;
        default:
            ESP_LOGE("error", "%s", message);
    }

    current_error = type;
    error_count[type]++;
    if (error_count[type] >= MAX_ERROR_COUNT || type == ASSERT)
    {
        error_draw_message(message);
        ulp_riscv_halt();
        esp_sleep_enable_timer_wakeup(UINT64_MAX);
    } else {
        deferred_uS = (5ULL * 1000ULL * 1000ULL) << error_count[type]; // Exponential backoff, up to ~1.5 hours
        esp_sleep_enable_timer_wakeup(deferred_uS);
    }
    esp_deep_sleep_start();
}

/* Reset error state, used after a successful run to allow for retries after transient errors */
static void error_reset()
{
    current_error = NO_ERROR;
    memset(error_count, 0, sizeof(error_count));
}

/* Helper function to check esp_err_t return values and call error handler if needed */
static void error_esp(enum error_type type, esp_err_t err)
{
    if (unlikely(err != ESP_OK))
    {
        const char *error_message = esp_err_to_name(err);
        error_handler(type, error_message);
    }
}


static void error_check(bool condition, enum error_type type, const char *message)
{
    if (unlikely(!condition))
    {
        error_handler(type, message);
    }
}

static uint32_t battery_get_voltage()
{
    int voltage;
    adc_oneshot_unit_handle_t adc_handle;
    adc_oneshot_unit_init_cfg_t adc_config =
    {
        .unit_id = ADC_UNIT_1,
        .ulp_mode = ADC_ULP_MODE_DISABLE,
    };
    ESP_ERROR_CHECK(adc_oneshot_new_unit(&adc_config, &adc_handle));
    adc_oneshot_chan_cfg_t adc_chan_config =
    {
        .bitwidth = ADC_BITWIDTH_12,
        .atten = ADC_ATTEN_DB_12,
    };
    ESP_ERROR_CHECK(adc_oneshot_config_channel(adc_handle, ADC1_GPIO5_CHANNEL, &adc_chan_config));
    adc_cali_handle_t cali_handle;
    adc_cali_curve_fitting_config_t cali_config =
    {
        .unit_id = ADC_UNIT_1,
        .atten = ADC_ATTEN_DB_12,
        .bitwidth = ADC_BITWIDTH_12,
    };
    ESP_ERROR_CHECK(adc_cali_create_scheme_curve_fitting(&cali_config, &cali_handle));
    ESP_ERROR_CHECK(adc_oneshot_get_calibrated_result(adc_handle, cali_handle, ADC1_GPIO5_CHANNEL, &voltage));
    ESP_LOGI("battery", "Battery voltage: %dmV", (voltage * 2));

    return (voltage * 2); // Voltage divider halves the voltage for measurement, so multiply by 2 to get actual voltage
}

static uint8_t battery_get_percentage()
{
    float voltage = ((float)battery_get_voltage()) / 1000, // Convert mV to V
        /* Polynomial regression to fit the discharge curve of a typical Lipo battery, clamped to 0-100% */
          percentage = 123 - (123 / pow((1 + pow((voltage / 3.7), 80)), 0.165));
    uint8_t percentage_clamped = (percentage < 0) ? 0 : ((percentage > 100) ? 100 : (uint8_t)round(percentage));
    ESP_LOGI("battery", "Battery percentage: %d%%", percentage_clamped);
    return percentage_clamped;
}

static esp_err_t http_event_handler(esp_http_client_event_t *evt)
{
    switch (evt->event_id)
    {
        case HTTP_EVENT_ERROR:
            ESP_LOGI("http", "HTTP_EVENT_ERROR");
            return ESP_FAIL;
        case HTTP_EVENT_ON_CONNECTED:
            ESP_LOGI("http", "HTTP_EVENT_ON_CONNECTED");
            break;
        case HTTP_EVENT_HEADER_SENT:
            ESP_LOGI("http", "HTTP_EVENT_HEADER_SENT");
            break;
        case HTTP_EVENT_ON_HEADER:
            ESP_LOGI("http", "HTTP_EVENT_ON_HEADER, key=%s, value=%s", evt->header_key, evt->header_value);
            break;
        case HTTP_EVENT_ON_DATA:
            ESP_LOGI("http", "HTTP_EVENT_ON_DATA, len=%d", evt->data_len);
            break;
        case HTTP_EVENT_ON_FINISH:
            ESP_LOGI("http", "HTTP_EVENT_ON_FINISH");
            break;
        case HTTP_EVENT_DISCONNECTED:
            ESP_LOGI("http", "HTTP_EVENT_DISCONNECTED");
            break;
        case HTTP_EVENT_REDIRECT:
            ESP_LOGI("http", "HTTP_EVENT_REDIRECT");
            break;
    }
    return ESP_OK;
}

static void wifi_event_handler(void *arg, esp_event_base_t event_base,
                          int32_t event_id, void *event_data)
{
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START)
    {
        esp_wifi_connect();
    }
    else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED)
    {
        if (retry_num < MAX_RETRY_NUM)
        {
            esp_wifi_connect();
            retry_num++;
            ESP_LOGI("wifi", "Failed to connect to the AP, retrying... (%d/%d)", retry_num, MAX_RETRY_NUM);
        } else {
            xEventGroupSetBits(wifi_event_group, WIFI_FAIL_BIT);
        }
        ESP_LOGI("wifi", "Disconnected from the AP");
    }
    else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP)
    {
        xEventGroupSetBits(wifi_event_group, WIFI_CONNECTED_BIT);
    }
}

static esp_netif_t *wifi_start()
{
    /* Default event loop must be created before create_default_wifi_sta() is called */
    wifi_event_group = xEventGroupCreate();
    error_check(wifi_event_group != NULL, MEMORY_ERROR, "Failed to create Wi-Fi event group");
    error_esp(WIFI_ERROR, esp_event_loop_create_default());

    /* Create Network Interface */
    error_esp(WIFI_ERROR, esp_netif_init());
    esp_netif_t *wifi = esp_netif_create_default_wifi_sta();
    error_check(wifi != NULL, MEMORY_ERROR, "Failed to create default Wi-Fi station");
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    error_esp(WIFI_ERROR, esp_wifi_init(&cfg));

    /* Setup event loop and handlers */
    esp_event_handler_instance_t instance_any_id;
    esp_event_handler_instance_t instance_got_ip;
    error_esp(WIFI_ERROR,
            esp_event_handler_instance_register(WIFI_EVENT,
                                                ESP_EVENT_ANY_ID,
                                                &wifi_event_handler,
                                                NULL,
                                                &instance_any_id));
    error_esp(WIFI_ERROR,
            esp_event_handler_instance_register(IP_EVENT,
                                                IP_EVENT_STA_GOT_IP,
                                                &wifi_event_handler,
                                                NULL,
                                                &instance_got_ip));

    /* Configure Wi-Fi connection and start the interface */
    wifi_config_t wifi_config =
    {
        .sta =
        {
            .ssid = WIFI_SSID,
            .password = WIFI_PASSWORD
        }
    };
    error_esp(WIFI_ERROR, esp_wifi_set_mode(WIFI_MODE_STA));
    error_esp(WIFI_ERROR, esp_wifi_set_config(WIFI_IF_STA, &wifi_config));

    /* Start Wi-Fi */
    error_esp(WIFI_ERROR, esp_wifi_start());
    ESP_LOGI("wifi", "Wi-Fi initialization completed.");

    /* Wait for connection or failure */
    EventBits_t bits = xEventGroupWaitBits(wifi_event_group,
            WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
            pdFALSE,
            pdFALSE,
            portMAX_DELAY);
    vEventGroupDelete(wifi_event_group);

    error_check((bits & WIFI_CONNECTED_BIT), WIFI_ERROR, "Failed to connect to Wi-Fi");
    ESP_LOGI("wifi", "Connected to AP");

    return wifi;
}

static void wifi_stop(esp_netif_t *netif)
{
    error_esp(WIFI_ERROR, esp_wifi_stop());
    error_esp(WIFI_ERROR, esp_wifi_deinit());
    esp_netif_destroy_default_wifi(netif);
}

static void https_get_weather()
{
    const esp_http_client_config_t config =
    {
        .host = "api.openweathermap.org",
        .path =
            "/data/3.0/onecall?units=imperial&lat=" LATITUDE "&lon=" LONGITUDE "&exclude=minutely,alerts&appid=" API_KEY,
        .transport_type = HTTP_TRANSPORT_OVER_SSL,
        .event_handler = http_event_handler,
        .cert_pem = (char *)server_cert_pem_start
    };
    ESP_LOGI("http", "HTTP client configured with host=%s, path=%s", config.host, config.path);
    ESP_LOGI("http", "Getting weather data...");

    esp_http_client_handle_t client = esp_http_client_init(&config);
    esp_http_client_set_method(client, HTTP_METHOD_GET);
    error_esp(WEATHER_ERROR, esp_http_client_open(client, 0));
    int content_length = esp_http_client_fetch_headers(client);
    error_check(content_length > 0, WEATHER_ERROR, "Failed to fetch HTTP headers");

    char *buffer = malloc(content_length + 1);
    error_check(buffer != NULL, MEMORY_ERROR, "Failed to allocate memory for HTTP response");

    int read_len = esp_http_client_read(client, buffer, content_length);
    error_check(read_len > 0, WEATHER_ERROR, "Failed to read HTTP response");
    buffer[read_len] = '\0';
    ESP_LOGV("http", "Received data: %s", buffer);

    cJSON *json = cJSON_ParseWithLength(buffer, content_length);
    if (unlikely(json == NULL))
    {
        const char *error_ptr = cJSON_GetErrorPtr();
        if (error_ptr != NULL)
        {
            error_handler(WEATHER_ERROR, error_ptr);
        }
    } else {
        /* Assertions are used here because if the API response doesn't match the expected format then
         * it means the API has changed and the code needs to be updated. */
        cJSON *current = cJSON_GetObjectItem(json, "current");

        cJSON *weather_array = cJSON_GetObjectItem(current, "weather");
        error_check(cJSON_IsArray(weather_array), ASSERT, "Expected 'weather' to be an array");
        error_check(cJSON_GetArraySize(weather_array) > 0, ASSERT,
                "Expected 'weather' array to have at least one item");
        cJSON *weather_item = cJSON_GetArrayItem(weather_array, 0),
              *description = cJSON_GetObjectItem(weather_item, "description"),
              *id = cJSON_GetObjectItem(weather_item, "id");
        error_check(cJSON_IsString(description) && cJSON_IsNumber(id), ASSERT,
                "Expected 'description' to be a string and 'id' to be a number");
        weather.id = id->valueint;
        snprintf(weather.description, sizeof(weather.description), "%s", description->valuestring);
        ESP_LOGI("weather", "Current Weather: %s (ID: %d)", weather.description, weather.id);

        cJSON *temp = cJSON_GetObjectItem(current, "temp"),
              *feels_like = cJSON_GetObjectItem(current, "feels_like");
        error_check(cJSON_IsNumber(temp) && cJSON_IsNumber(feels_like), ASSERT,
                "Expected 'temp' and 'feels_like' to be numbers");
        weather.current_temp = temp->valuedouble;
        weather.feels_like_temp = feels_like->valuedouble;
        ESP_LOGI("weather", "Current Temp: %.2f F Feels Like: %.2f F",
                weather.current_temp, weather.feels_like_temp);

        cJSON *wind_speed = cJSON_GetObjectItem(current, "wind_speed"),
              *wind_direction = cJSON_GetObjectItem(current, "wind_deg"),
              *cloudiness = cJSON_GetObjectItem(current, "clouds");
        error_check(cJSON_IsNumber(wind_speed) && cJSON_IsNumber(wind_direction) && cJSON_IsNumber(cloudiness),
                ASSERT, "Expected 'wind_speed', 'wind_deg', and 'clouds' to be numbers");
        weather.wind_speed = wind_speed->valuedouble;
        weather.wind_direction_degrees = wind_direction->valueint;
        weather.cloudiness = cloudiness->valuedouble;
        ESP_LOGI("weather", "Wind Speed: %.2f mph at %d degrees Cloudiness: %.2f%%",
                weather.wind_speed, weather.wind_direction_degrees, weather.cloudiness);

        cJSON *hourly_array = cJSON_GetObjectItem(json, "hourly");
        error_check(cJSON_IsArray(hourly_array), ASSERT, "Expected 'hourly' to be an array");
        error_check(cJSON_GetArraySize(hourly_array) >= FORECAST_HOURS, ASSERT,
                "Expected 'hourly' array to have at least " STRINGIFY(FORECAST_HOURS) " items");
        for (int i = 0; i < FORECAST_HOURS; i++)
        {
            cJSON *hourly_item = cJSON_GetArrayItem(hourly_array, i),
                  *temp = cJSON_GetObjectItem(hourly_item, "temp"),
                  *precipitation_chance = cJSON_GetObjectItem(hourly_item, "pop"),
                  *dt = cJSON_GetObjectItem(hourly_item, "dt");
            error_check(cJSON_IsNumber(temp) && cJSON_IsNumber(precipitation_chance) && cJSON_IsNumber(dt), ASSERT,
                    "Expected 'temp', 'pop', and 'dt' to be numbers in hourly forecast");
            hourly_forecast[i].temp = temp->valuedouble;
            hourly_forecast[i].precipitation_chance = precipitation_chance->valuedouble * 100;
            time_t dt_time_t = (time_t)dt->valuedouble;
            ESP_LOGI("hourly", "Raw time for hour %d: %lld", i + 1, dt_time_t);
            struct tm dt_timeinfo;
            localtime_r(&dt_time_t, &dt_timeinfo);
            strftime(hourly_forecast[i].time, sizeof(hourly_forecast[i].time), "%I%p", &dt_timeinfo);
            ESP_LOGI("hourly", "Hour %d Temp: %.2f F Precipitation Chance: %.2f%% at %s",
                    i + 1, hourly_forecast[i].temp, hourly_forecast[i].precipitation_chance,
                    hourly_forecast[i].time);
        }
        cJSON *daily_array = cJSON_GetObjectItem(json, "daily");
        error_check(cJSON_IsArray(daily_array), ASSERT, "Expected 'daily' to be an array");
        error_check(cJSON_GetArraySize(daily_array) >= FORECAST_DAYS, ASSERT,
                "Expected 'daily' array to have at least " STRINGIFY(FORECAST_DAYS) " items");
        for (int i = 0; i < FORECAST_DAYS; i++)
        {
            cJSON *forecast_item = cJSON_GetArrayItem(daily_array, i),
                  *temp = cJSON_GetObjectItem(forecast_item, "temp");
            error_check(cJSON_IsObject(temp), ASSERT, "Expected 'temp' to be an object in daily forecast");

            cJSON *temp_min = cJSON_GetObjectItem(temp, "min"),
                  *temp_max = cJSON_GetObjectItem(temp, "max"),
                  *precipitation_chance = cJSON_GetObjectItem(forecast_item, "pop");
            error_check(cJSON_IsNumber(temp_min) && cJSON_IsNumber(temp_max) && cJSON_IsNumber(precipitation_chance),
                    ASSERT, "Expected 'min', 'max', and 'pop' to be numbers in daily forecast");
            forecast[i].low_temp = temp_min->valuedouble;
            forecast[i].high_temp = temp_max->valuedouble;
            forecast[i].precipitation_chance = precipitation_chance->valuedouble;
            ESP_LOGI("forecast", "Day %d Low Temp: %.2f F High Temp: %.2f F Precipitation Chance: %.2f%%",
                    i + 1, forecast[i].low_temp, forecast[i].high_temp, forecast[i].precipitation_chance * 100);

            cJSON *weather_array = cJSON_GetObjectItem(forecast_item, "weather");
            error_check(cJSON_IsArray(weather_array), ASSERT, "Expected 'weather' to be an array in daily forecast");
            error_check(cJSON_GetArraySize(weather_array) > 0, ASSERT,
                    "Expected 'weather' array to have at least one item in daily forecast");
            cJSON *weather_item = cJSON_GetArrayItem(weather_array, 0),
                  *id = cJSON_GetObjectItem(weather_item, "id");
            error_check(cJSON_IsNumber(id), ASSERT, "Expected 'id' to be a number in daily forecast weather");
            forecast[i].id = id->valueint;
            ESP_LOGI("forecast", "Day %d Weather ID: %d", i + 1, forecast[i].id);

            cJSON *dt = cJSON_GetObjectItem(forecast_item, "dt");
            error_check(cJSON_IsNumber(dt), ASSERT, "Expected 'dt' to be a number in daily forecast");
            time_t dt_time_t = (time_t)dt->valuedouble;
            struct tm dt_timeinfo;
            localtime_r(&dt_time_t, &dt_timeinfo);
            strftime(forecast[i].day, sizeof(forecast[i].day), "%a.", &dt_timeinfo);
            ESP_LOGI("forecast", "Day %d Date: %s", i + 1, forecast[i].day);
        }
        weather.low_temp = forecast[0].low_temp;
        weather.high_temp = forecast[0].high_temp;
    }

    cJSON_Delete(json);
    esp_http_client_close(client);
    esp_http_client_cleanup(client);
    free(buffer);
}

static bool sntp_get_nvs_time()
{
    nvs_handle_t nvs_handle;
    error_esp(SNTP_ERROR, nvs_open("storage", NVS_READONLY, &nvs_handle));
    if (nvs_get_i64(nvs_handle, "timestamp", &now) == ESP_OK)
    {
        ESP_LOGI("sntp", "Retrieved timestamp from NVS: %lld", now);
        localtime_r(&now, &timeinfo);
        nvs_close(nvs_handle);
        return true;
    } else {
        ESP_LOGI("sntp", "No timestamp found in NVS");
        nvs_close(nvs_handle);
        return false;
    }
}

static void sntp_set_nvs_time()
{
    nvs_handle_t nvs_handle;
    error_esp(SNTP_ERROR, nvs_open("storage", NVS_READWRITE, &nvs_handle));
    error_esp(SNTP_ERROR, nvs_set_i64(nvs_handle, "timestamp", now));
    nvs_close(nvs_handle);
    ESP_LOGI("sntp", "Saved timestamp to NVS: %lld", now);
}

static void sntp_sync_time()
{
    esp_sntp_config_t sntp_config = ESP_NETIF_SNTP_DEFAULT_CONFIG("pool.ntp.org");
    esp_netif_sntp_init(&sntp_config);

    /* POSIX timezones */
    setenv("TZ", "CST6CDT,M3.2.0,M11.1.0", 1); // CST
    tzset();

    error_esp(SNTP_ERROR, esp_netif_sntp_sync_wait(pdMS_TO_TICKS(10000)));
    ESP_LOGI("sntp", "Time synchronized successfully");

    UPDATE_TIME;
    sntp_set_nvs_time();
    char timeinfo_str[64];
    strftime(timeinfo_str, sizeof(timeinfo_str), "%Y-%m-%d %H:%M:%S", &timeinfo);
    ESP_LOGI("sntp", "Current time: %s", timeinfo_str);
    esp_netif_sntp_deinit();
}

static void rtc_gpio_init_all()
{
    const gpio_num_t all_pins[] = {CS_PIN, DC_PIN, RST_PIN, BUSY_PIN, MOSI_PIN, SCK_PIN};
    for (int i = 0; i < sizeof(all_pins) / sizeof(all_pins[0]); i++)
    {
        error_check(rtc_gpio_is_valid_gpio(all_pins[i]), ASSERT, "Invalid GPIO pin");
        gpio_reset_pin(all_pins[i]);
        rtc_gpio_init(all_pins[i]);
        if (all_pins[i] == BUSY_PIN)
        {
            rtc_gpio_set_direction(all_pins[i], RTC_GPIO_MODE_INPUT_ONLY);
        } else {
            rtc_gpio_set_direction(all_pins[i], RTC_GPIO_MODE_OUTPUT_ONLY);
        }
        rtc_gpio_pulldown_dis(all_pins[i]);
        rtc_gpio_pullup_dis(all_pins[i]);
        gpio_intr_disable(all_pins[i]);
    }
    rtc_gpio_set_level(RST_PIN, HIGH);
}

static void rtc_gpio_set_low_all()
{
    rtc_gpio_set_level(CS_PIN, LOW);
    rtc_gpio_set_level(DC_PIN, LOW);
    rtc_gpio_set_level(RST_PIN, LOW);
    rtc_gpio_set_level(MOSI_PIN, LOW);
    rtc_gpio_set_level(SCK_PIN, LOW);
}

static void align_time_to_next_minute()
{
    UPDATE_TIME;
    int seconds_to_next_minute = 60 - timeinfo.tm_sec;
    ESP_LOGI("time",
            "Current time: %02d:%02d:%02d, sleeping for %d seconds to align to next minute",
            timeinfo.tm_hour, timeinfo.tm_min, timeinfo.tm_sec, seconds_to_next_minute);

    // TODO: This consumes alot of power, change to altering the ULP wakeup time
    vTaskDelay((seconds_to_next_minute * 1000) / portTICK_PERIOD_MS);

    UPDATE_TIME;
    ulp_hours = timeinfo.tm_hour % 12;
    ulp_hours = (ulp_hours == 0) ? 12 : ulp_hours;
    ulp_minutes = timeinfo.tm_min;
}

static void task_wifi_start(void *pvParameters)
{
    wifi_if = wifi_start();
    xEventGroupSetBits(event_group, WIFI_DONE_BIT);
    ESP_LOGI("wifi", "Wi-Fi task complete, bit set");
    vTaskDelete(NULL);
}

static void task_sntp_sync_time(void *pvParameters)
{
    ESP_LOGI("sntp", "Waiting for Wi-Fi to be connected...");
    xEventGroupWaitBits(event_group, WIFI_DONE_BIT, pdFALSE, pdTRUE, portMAX_DELAY);
    sntp_sync_time();
    xEventGroupSetBits(event_group, SNTP_DONE_BIT);
    ESP_LOGI("sntp", "SNTP sync task complete, bit set");
    vTaskDelete(NULL);
}

static void task_https_get_weather(void *pvParameters)
{
    ESP_LOGI("weather", "Waiting for Wi-Fi to be connected...");
    xEventGroupWaitBits(event_group, WIFI_DONE_BIT, pdFALSE, pdTRUE, portMAX_DELAY);
    if (sntp_get_nvs_time())
    {
        ESP_LOGI("weather", "Time obtained from NVS, not waiting for SNTP sync");
    } else {
        ESP_LOGI("weather", "No time in NVS, waiting for SNTP sync to complete...");
        xEventGroupWaitBits(event_group, SNTP_DONE_BIT, pdFALSE, pdTRUE, portMAX_DELAY);
    }
    ESP_LOGI("weather", "Finished waiting for dependencies, starting weather data retrieval");
    https_get_weather();
    xEventGroupSetBits(event_group, WEATHER_DONE_BIT);
    ESP_LOGI("weather", "Weather data retrieval complete");
    vTaskDelete(NULL);
}

void app_main()
{
    vTaskDelay(2000 / portTICK_PERIOD_MS); // Delay for serial monitor
    /* Default log level is set to ERROR to speed up boot time, set it back to INFO */
    esp_log_level_set("*", ESP_LOG_INFO);
    rtc_gpio_init_all();

    battery_percentage = battery_get_percentage();
    error_check((battery_percentage > BATTERY_THRESHOLD), OTHER_ERROR, "Battery percentage is critically low");

    /* Wi-Fi requires NVS flash to store credentials otherwise it will fail to initialize */
    esp_err_t ret = nvs_flash_init();
    if (unlikely(ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND))
    {
        error_esp(OTHER_ERROR, nvs_flash_erase());
        error_esp(OTHER_ERROR, nvs_flash_init());
    }

    esp_sleep_wakeup_cause_t wakeup_cause = esp_sleep_get_wakeup_cause();
    // TODO: If woken up from ULP draw next minutes frame
    if (wakeup_cause == ESP_SLEEP_WAKEUP_ULP || wakeup_cause == ESP_SLEEP_WAKEUP_TIMER)
    {
        ESP_LOGI("main", "Woken up from deep sleep");
    } else {
        /* Init ULP so its variables can be accessed and modified from the main CPU */
        error_esp(OTHER_ERROR, ulp_riscv_load_binary(bin_start, (bin_end - bin_start)));
        ulp_set_wakeup_period(0, 10);
        error_esp(OTHER_ERROR, ulp_riscv_run()); // Exits immediately after starting
    }
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON); // Keep GPIO pins enabled in deep sleep
    esp_sleep_pd_config(ESP_PD_DOMAIN_RC_FAST, ESP_PD_OPTION_ON); // Keep RTC fast clock on for ULP
    ulp_clk_cal = rtc_clk_cal(RTC_CAL_RTC_MUX, 1000); // Calibrate RTC clock against main one
    error_check(ulp_clk_cal != 0, OTHER_ERROR, "Failed to calibrate RTC clock");

    event_group = xEventGroupCreate();
    error_check(event_group != NULL, MEMORY_ERROR, "Failed to create event group for task synchronization");
    xTaskCreate(task_wifi_start, "wifi_start", 4096, NULL, 5, NULL);
    xTaskCreate(task_sntp_sync_time, "sntp_sync_time", 4096, NULL, 5, NULL);
    xTaskCreate(task_https_get_weather, "https_get_weather", 65536, NULL, 5, NULL);

    xEventGroupWaitBits(event_group, ALL_DONE_BITS, pdFALSE, pdTRUE, portMAX_DELAY);
    wifi_stop(wifi_if);
    vEventGroupDelete(event_group);
    ESP_LOGI("main", "All tasks complete, proceeding to draw frame and enter deep sleep");

    epd_init();
    frame_draw_default();
    epd_write_frame();
    epd_sleep();
    rtc_gpio_set_low_all();

    align_time_to_next_minute();
    ulp_set_wakeup_period(0, (60ULL * 1000ULL * 1000ULL)); // 60 seconds in uS
    ulp_riscv_timer_resume();

    error_esp(OTHER_ERROR, esp_sleep_enable_ulp_wakeup());
    esp_sleep_enable_timer_wakeup(180ULL * 60ULL * 1000ULL * 1000ULL); // 3 hours in uS
    error_reset(); // Reset error state after a successful run
    esp_deep_sleep_start();
}
