#include <time.h>
#include <math.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_event.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_http_client.h"
#include "esp_netif_sntp.h"
#include "esp_sleep.h"
#include "nvs_flash.h"
#include "cJSON.h"
#include "driver/gpio.h"
#include "driver/rtc_io.h"
#include "soc/rtc.h"
#include "ulp_riscv.h"
#include "display.h"
#include "fonts.h"
#include "icons.h"
#include "ulp_main.h" // Generated by CMake, extern declarations for ULP variables
#include "secret.h" // Not included in repo
/* ^ Defines:
 * - WIFI_SSID
 * - WIFI_PASSWORD
 * - LATITUDE
 * - LONGITUDE
 * - API_KEY
 */

/* Following functions are placed in IRAM as they are frequently called:
 * - spi_write_byte: called by all SPI write functions
 * - spi_write_command: called for every command sent to the display
 * - spi_write_data: called for every byte of data sent to the display
 * - frame_draw_byte: called by all frame drawing functions */

// TODO: use espidf heap tracing to check for memory leaks
// TODO: go through and correctly handle all the ESP_ERROR_CHECKS
/* Main event group */
static EventGroupHandle_t event_group = NULL;
#define WIFI_DONE_BIT BIT0
#define SNTP_DONE_BIT BIT1
#define WEATHER_DONE_BIT BIT2
#define ALL_DONE_BITS (WIFI_DONE_BIT | SNTP_DONE_BIT | WEATHER_DONE_BIT)

/* Wall clock time */
static time_t now;
static struct tm timeinfo;
#define UPDATE_TIME time(&now); localtime_r(&now, &timeinfo)

/* Wifi definitions and variables */
static EventGroupHandle_t wifi_event_group;
static int retry_num = 0;
static esp_netif_t *wifi_if = NULL;
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1
#define MAX_RETRY_NUM      5

/* Root server certificate for api.openweathermap.org embedded by CMake */
extern const uint8_t server_cert_pem_start[] asm("_binary_openweather_pem_start");
extern const uint8_t server_cert_pem_end[]   asm("_binary_openweather_pem_end");

/* ULP binary embedded by CMake */
extern const uint8_t bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t bin_end[]   asm("_binary_ulp_main_bin_end");

/* Weather id definitions */
#define THUNDERSTORM_START  200
#define DRIZZLE_START       300
#define RAIN_START          500
#define SNOW_START          600
#define ATMOSPHERE_START    700
#define CLEAR_SKY           800
#define CLOUDS_START        801

/* Current weather conditions doesn't store all returned data from API
 * just those that are displayed */
static struct weather_today
{
    uint16_t id; // Weather condition code that corresponds to an icon
    char description[32];
    float current_temp;
    float feels_like_temp;
    float high_temp;
    float low_temp;
    float wind_speed;
    uint16_t wind_direction_degrees; // Degrees from north that the wind is coming from
    float precipitation; // mm of rain/snow in the last hour
    float cloudiness; // % of sky covered by clouds
} weather;

#define FORECAST_HOURS 12
static struct hourly_forecast
{
    float temp;
    float precipitation_chance;
} hourly_forecast[FORECAST_HOURS];

#define FORECAST_DAYS 5
static struct weather_forecast
{
    uint16_t id;
    char description[32];
    float high_temp;
    float low_temp;
    float wind_speed;
    float precipitation_chance;
    float cloudiness;
} forecast[FORECAST_DAYS];

static uint8_t frame[EPD_HEIGHT][EPD_BYTE_WIDTH];

// TODO: Check esp_err_t return value
static esp_err_t http_event_handler(esp_http_client_event_t *evt)
{
    /* Most of these events should never happen, but I'm including them
     * for completeness and debugging purposes */
    switch (evt->event_id)
    {
        case HTTP_EVENT_ERROR:
            ESP_LOGI("http", "HTTP_EVENT_ERROR");
            break;
        case HTTP_EVENT_ON_CONNECTED:
            ESP_LOGI("http", "HTTP_EVENT_ON_CONNECTED");
            break;
        case HTTP_EVENT_HEADER_SENT:
            ESP_LOGI("http", "HTTP_EVENT_HEADER_SENT");
            break;
        case HTTP_EVENT_ON_HEADER:
            ESP_LOGI("http", "HTTP_EVENT_ON_HEADER, key=%s, value=%s", evt->header_key, evt->header_value);
            break;
        case HTTP_EVENT_ON_DATA:
            ESP_LOGI("http", "HTTP_EVENT_ON_DATA, len=%d", evt->data_len);
            break;
        case HTTP_EVENT_ON_FINISH:
            ESP_LOGI("http", "HTTP_EVENT_ON_FINISH");
            break;
        case HTTP_EVENT_DISCONNECTED:
            ESP_LOGI("http", "HTTP_EVENT_DISCONNECTED");
            break;
        case HTTP_EVENT_REDIRECT:
            ESP_LOGI("http", "HTTP_EVENT_REDIRECT");
            break;
    }
    return ESP_OK;
}

static void wifi_event_handler(void *arg, esp_event_base_t event_base,
                          int32_t event_id, void *event_data)
{
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START)
    {
        esp_wifi_connect();
    }
    else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED)
    {
        if (retry_num < MAX_RETRY_NUM)
        {
            esp_wifi_connect();
            retry_num++;
            ESP_LOGI("wifi", "Failed to connect to the AP, retrying... (%d/%d)", retry_num, MAX_RETRY_NUM);
        } else {
            xEventGroupSetBits(wifi_event_group, WIFI_FAIL_BIT);
        }
        ESP_LOGI("wifi", "Disconnected from the AP");
    }
    else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP)
    {
        xEventGroupSetBits(wifi_event_group, WIFI_CONNECTED_BIT);
    }
}

static esp_netif_t *wifi_start()
{
    // TODO: If ESP_ERROR returns an error restart the board and try again.
    // preferably the ULP should continue to update the time on the display
    /* Default event loop must be created before create_default_wifi_sta() is called */
    wifi_event_group = xEventGroupCreate();
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_event_loop_create_default());

    /* Create Network Interface */
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_netif_init());
    esp_netif_t *wifi = esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_wifi_init(&cfg));

    /* Setup event loop and handlers */
    esp_event_handler_instance_t instance_any_id;
    esp_event_handler_instance_t instance_got_ip;
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_event_handler_instance_register(WIFI_EVENT,
                                                                ESP_EVENT_ANY_ID,
                                                                &wifi_event_handler,
                                                                NULL,
                                                                &instance_any_id));
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_event_handler_instance_register(IP_EVENT,
                                                                IP_EVENT_STA_GOT_IP,
                                                                &wifi_event_handler,
                                                                NULL,
                                                                &instance_got_ip));

    /* Configure Wi-Fi connection and start the interface */
    wifi_config_t wifi_config = {
        .sta = {
            .ssid = WIFI_SSID,
            .password = WIFI_PASSWORD
        }
    };
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));

    /* Start Wi-Fi */
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_wifi_start());
    ESP_LOGI("wifi", "Wi-Fi initialization completed.");

    /* Wait for connection or failure */
    EventBits_t bits = xEventGroupWaitBits(wifi_event_group,
            WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
            pdFALSE,
            pdFALSE,
            portMAX_DELAY);
    vEventGroupDelete(wifi_event_group);

    if (bits & WIFI_CONNECTED_BIT)
    {
        ESP_LOGI("wifi", "Connected to AP");
    }
    // TODO: Need to handle failure eventually and retry after 10 minutes
    else if (bits & WIFI_FAIL_BIT)
    {
        ESP_LOGI("wifi", "Failed to connect to AP");
    } else {
        ESP_LOGE("wifi", "UNEXPECTED EVENT");
    }

    return wifi;
}

static void wifi_stop(esp_netif_t *netif)
{
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_wifi_stop());
    ESP_ERROR_CHECK_WITHOUT_ABORT(esp_wifi_deinit());
    esp_netif_destroy_default_wifi(netif);
}

static void https_get_weather()
{
    // TODO: Compress everything into one http GET request with 3.0 onecall
    esp_http_client_config_t config =
    {
        .host = "api.openweathermap.org",
        .path = "/data/2.5/weather?units=imperial&lat=" LATITUDE "&lon=" LONGITUDE "&appid=" API_KEY,
        .transport_type = HTTP_TRANSPORT_OVER_SSL,
        .event_handler = http_event_handler,
        .cert_pem = (char *)server_cert_pem_start
    };
    ESP_LOGI("http", "HTTP client configured with host=%s, path=%s", config.host, config.path);
    ESP_LOGI("http", "Getting todays weather...");

    esp_http_client_handle_t client = esp_http_client_init(&config);
    esp_http_client_set_method(client, HTTP_METHOD_GET);
    esp_err_t err = esp_http_client_open(client, 0);
    if (err != ESP_OK)
    {
        ESP_LOGE("http", "HTTP GET request failed: %s", esp_err_to_name(err));
        // TODO: Schedule retry after 10 minutes
    }
    int content_length = esp_http_client_fetch_headers(client);

    char *buffer = malloc(content_length + 1);
    assert(buffer != NULL); // malloc shouldn't fail unless there's a memory leak
    int read_len = esp_http_client_read(client, buffer, content_length);
    if (read_len >= 0)
    {
        buffer[read_len] = '\0';
        ESP_LOGV("http", "Received data: %s", buffer);
    }
    else
    {
        ESP_LOGE("http", "Failed to read response");
    }

    /* Parse JSON response and populate the weather struct */
    cJSON *json = cJSON_ParseWithLength(buffer, content_length);
    if (json == NULL)
    {
        // TODO: Schedule retry after 10 minutes
        const char *error_ptr = cJSON_GetErrorPtr();
        if (error_ptr != NULL)
        {
            ESP_LOGE("json", "Error before: %s", error_ptr);
        }
    } else {
        /* Assertions are used here because if the API response doesn't match the expected format then
         * it means the API has changed and the code needs to be updated. */
        cJSON *weather_array = cJSON_GetObjectItem(json, "weather");
        assert(cJSON_IsArray(weather_array));
        // weather is an array but only ever returns one item
        assert(cJSON_GetArraySize(weather_array) > 0);
        cJSON *weather_item = cJSON_GetArrayItem(weather_array, 0);
        cJSON *description = cJSON_GetObjectItem(weather_item, "description");
        if (cJSON_IsString(description))
        {
            strncpy(weather.description, description->valuestring, sizeof(weather.description) - 1);
            weather.description[sizeof(weather.description) - 1] = '\0';
            ESP_LOGI("weather", "Description: %s", weather.description);
        }
        cJSON *id = cJSON_GetObjectItem(weather_item, "id");
        if (cJSON_IsNumber(id))
        {
            weather.id = id->valueint;
            ESP_LOGI("weather", "Weather ID: %d", weather.id);
        }

        cJSON *main = cJSON_GetObjectItem(json, "main");
        assert(cJSON_IsObject(main));
        cJSON *temp = cJSON_GetObjectItem(main, "temp");
        if (cJSON_IsNumber(temp))
        {
            weather.current_temp = temp->valuedouble;
            ESP_LOGI("weather", "Current Temp: %.2f F", weather.current_temp);
        }
        cJSON *feels_like = cJSON_GetObjectItem(main, "feels_like");
        if (cJSON_IsNumber(feels_like))
        {
            weather.feels_like_temp = feels_like->valuedouble;
            ESP_LOGI("weather", "Feels Like Temp: %.2f F", weather.feels_like_temp);
        }
        cJSON *temp_min = cJSON_GetObjectItem(main, "temp_min");
        if (cJSON_IsNumber(temp_min))
        {
            weather.low_temp = temp_min->valuedouble;
            ESP_LOGI("weather", "Low Temp: %.2f F", weather.low_temp);
        }
        cJSON *temp_max = cJSON_GetObjectItem(main, "temp_max");
        if (cJSON_IsNumber(temp_max))
        {
            weather.high_temp = temp_max->valuedouble;
            ESP_LOGI("weather", "High Temp: %.2f F", weather.high_temp);
        }

        cJSON *wind = cJSON_GetObjectItem(json, "wind");
        assert(cJSON_IsObject(wind));
        cJSON *wind_speed = cJSON_GetObjectItem(wind, "speed");
        if (cJSON_IsNumber(wind_speed))
        {
            weather.wind_speed = wind_speed->valuedouble;
            ESP_LOGI("weather", "Wind Speed: %.2f mph", weather.wind_speed);
        }
        cJSON *wind_direction = cJSON_GetObjectItem(wind, "deg");
        if (cJSON_IsNumber(wind_direction))
        {
            weather.wind_direction_degrees = wind_direction->valueint;
            ESP_LOGI("weather", "Wind Direction: %d degrees", weather.wind_direction_degrees);
        }

        cJSON *clouds = cJSON_GetObjectItem(json, "clouds");
        assert(cJSON_IsObject(clouds));
        cJSON *cloudiness = cJSON_GetObjectItem(clouds, "all");
        if (cJSON_IsNumber(cloudiness))
        {
            weather.cloudiness = cloudiness->valuedouble;
            ESP_LOGI("weather", "Cloudiness: %.2f%%", weather.cloudiness);
        }

        /* Won't return anything if it hasn't rained in the last hour */
        cJSON *rain = cJSON_GetObjectItem(json, "rain");
        if (cJSON_IsObject(rain))
        {
            cJSON *rain_1h = cJSON_GetObjectItem(rain, "1h");
            if (cJSON_IsNumber(rain_1h))
            {
                weather.precipitation = rain_1h->valuedouble;
                ESP_LOGI("weather", "Precipitation (rain) in last hour: %.2f mm", weather.precipitation);
            }
        } else {
            ESP_LOGI("weather", "Not currently raining");
            weather.precipitation = -1; // Set negative to indicate no precipitation data
        }
    }
    free(buffer);
    // TODO: cJSON_Delete should free every JSON object under it, but I should check with valgrind
    cJSON_Delete(json);
    esp_http_client_close(client);

    config.path = "/data/2.5/forecast?units=imperial&lat=" LATITUDE "&lon=" LONGITUDE "&appid=" API_KEY;
    ESP_LOGI("http", "Getting weather forcasts...");
    client = esp_http_client_init(&config);
    esp_http_client_set_method(client, HTTP_METHOD_GET);
    err = esp_http_client_open(client, 0);
    if (err != ESP_OK)
    {
        ESP_LOGE("http", "HTTP GET request failed: %s", esp_err_to_name(err));
    }
    content_length = esp_http_client_fetch_headers(client);
    buffer = malloc(content_length + 1);
    assert(buffer != NULL);
    read_len = esp_http_client_read(client, buffer, content_length);
    if (read_len >= 0)
    {
        buffer[read_len] = '\0';
        ESP_LOGV("http", "Received data: %s", buffer);
    } else {
        ESP_LOGE("http", "Failed to read response");
    }

    /* Parse JSON response and populate the forecast array; data updates every three hours */
    json = cJSON_ParseWithLength(buffer, content_length);
    if (json == NULL)
    {
        const char *error_ptr = cJSON_GetErrorPtr();
        if (error_ptr != NULL)
        {
            ESP_LOGE("json", "Error before: %s", error_ptr);
        }
    } else {
        for (int i = 0; i < FORECAST_DAYS; i++)
        {
            cJSON *list = cJSON_GetObjectItem(json, "list");
            assert(cJSON_IsArray(list));
            cJSON *forecast_item = cJSON_GetArrayItem(list, i);
            cJSON *main = cJSON_GetObjectItem(forecast_item, "main");
            assert(cJSON_IsObject(main));
            cJSON *temp_min = cJSON_GetObjectItem(main, "temp_min");
            if (cJSON_IsNumber(temp_min))
            {
                forecast[i].low_temp = temp_min->valuedouble;
                ESP_LOGI("forecast", "Day %d Low Temp: %.2f F", i + 1, forecast[i].low_temp);
            }
            cJSON *temp_max = cJSON_GetObjectItem(main, "temp_max");
            if (cJSON_IsNumber(temp_max))
            {
                forecast[i].high_temp = temp_max->valuedouble;
                ESP_LOGI("forecast", "Day %d High Temp: %.2f F", i + 1, forecast[i].high_temp);
            }
            cJSON *wind = cJSON_GetObjectItem(forecast_item, "wind");
            assert(cJSON_IsObject(wind));
            cJSON *wind_speed = cJSON_GetObjectItem(wind, "speed");
            if (cJSON_IsNumber(wind_speed))
            {
                forecast[i].wind_speed = wind_speed->valuedouble;
                ESP_LOGI("forecast", "Day %d Wind Speed: %.2f mph", i + 1, forecast[i].wind_speed);
            }
            cJSON *clouds = cJSON_GetObjectItem(forecast_item, "clouds");
            assert(cJSON_IsObject(clouds));
            cJSON *cloudiness = cJSON_GetObjectItem(clouds, "all");
            if (cJSON_IsNumber(cloudiness))
            {
                forecast[i].cloudiness = cloudiness->valueint;
                ESP_LOGI("forecast", "Day %d Cloudiness: %d%%", i + 1, forecast[i].cloudiness);
            }
            cJSON *precipitation_chance = cJSON_GetObjectItem(forecast_item, "pop");
            if (cJSON_IsNumber(precipitation_chance))
            {
                forecast[i].precipitation_chance = precipitation_chance->valuedouble;
                ESP_LOGI("forecast", "Day %d Precipitation Chance: %.2f%%", i + 1, forecast[i].precipitation_chance * 100);
            }
            cJSON *weather_array = cJSON_GetObjectItem(forecast_item, "weather");
            assert(cJSON_IsArray(weather_array));
            assert(cJSON_GetArraySize(weather_array) > 0);
            cJSON *weather_item = cJSON_GetArrayItem(weather_array, 0);
            cJSON *description = cJSON_GetObjectItem(weather_item, "description");
            if (cJSON_IsString(description))
            {
                strncpy(forecast[i].description, description->valuestring, sizeof(forecast[i].description) - 1);
                forecast[i].description[sizeof(forecast[i].description) - 1] = '\0';
                ESP_LOGI("forecast", "Day %d Description: %s", i + 1, forecast[i].description);
            }
            cJSON *id = cJSON_GetObjectItem(weather_item, "id");
            if (cJSON_IsNumber(id))
            {
                forecast[i].id = id->valueint;
                ESP_LOGI("forecast", "Day %d Weather ID: %d", i + 1, forecast[i].id);
            }
        }
    }

    free(buffer);
    cJSON_Delete(json);
    esp_http_client_close(client);

    config.path = "/data/3.0/onecall?units=imperial&lat=" LATITUDE "&lon=" LONGITUDE "&exclude=current,minutely,daily,alerts&appid=" API_KEY;
    ESP_LOGI("http", "Getting hourly forcasts...");
    client = esp_http_client_init(&config);
    esp_http_client_set_method(client, HTTP_METHOD_GET);
    err = esp_http_client_open(client, 0);
    if (err != ESP_OK)
    {
        ESP_LOGE("http", "HTTP GET request failed: %s", esp_err_to_name(err));
    }
    content_length = esp_http_client_fetch_headers(client);
    buffer = malloc(content_length + 1);
    assert(buffer != NULL);
    read_len = esp_http_client_read(client, buffer, content_length);
    if (read_len >= 0)
    {
        buffer[read_len] = '\0';
        ESP_LOGV("http", "Received data: %s", buffer);
    } else {
        ESP_LOGE("http", "Failed to read response");
    }

    /* Parse JSON response and populate the forecast array; data updates every three hours */
    json = cJSON_ParseWithLength(buffer, content_length);
    if (json == NULL)
    {
        const char *error_ptr = cJSON_GetErrorPtr();
        if (error_ptr != NULL)
        {
            ESP_LOGE("json", "Error before: %s", error_ptr);
        }
    } else {
        cJSON *hourly_array = cJSON_GetObjectItem(json, "hourly");
        assert(cJSON_IsArray(hourly_array));
        for (int i = 0; i < FORECAST_HOURS; i++)
        {
            cJSON *hourly_item = cJSON_GetArrayItem(hourly_array, i);
            cJSON *temp = cJSON_GetObjectItem(hourly_item, "temp");
            if (cJSON_IsNumber(temp))
            {
                hourly_forecast[i].temp = temp->valuedouble;
                ESP_LOGI("hourly", "Hour %d Temp: %.2f F", i + 1, hourly_forecast[i].temp);
            }
            cJSON *precipitation_chance = cJSON_GetObjectItem(hourly_item, "pop");
            if (cJSON_IsNumber(precipitation_chance))
            {
                hourly_forecast[i].precipitation_chance = precipitation_chance->valuedouble;
                ESP_LOGI("hourly", "Hour %d Precipitation Chance: %.2f%%", i + 1, hourly_forecast[i].precipitation_chance * 100);
            }
        }
    }

    cJSON_Delete(json);
    esp_http_client_close(client);
    esp_http_client_cleanup(client);
    free(buffer);
}

static bool sntp_get_nvs_time()
{
    nvs_handle_t nvs_handle;
    ESP_ERROR_CHECK_WITHOUT_ABORT(nvs_open("storage", NVS_READONLY, &nvs_handle));
    if (nvs_get_i64(nvs_handle, "timestamp", &now) == ESP_OK)
    {
        ESP_LOGI("sntp", "Retrieved timestamp from NVS: %lld", now);
        localtime_r(&now, &timeinfo);
        nvs_close(nvs_handle);
        return true;
    } else {
        ESP_LOGI("sntp", "No timestamp found in NVS");
        nvs_close(nvs_handle);
        return false;
    }
}

static void sntp_set_nvs_time()
{
    nvs_handle_t nvs_handle;
    ESP_ERROR_CHECK_WITHOUT_ABORT(nvs_open("storage", NVS_READWRITE, &nvs_handle));
    ESP_ERROR_CHECK_WITHOUT_ABORT(nvs_set_i64(nvs_handle, "timestamp", now));
    nvs_close(nvs_handle);
    ESP_LOGI("sntp", "Saved timestamp to NVS: %lld", now);
}

static void sntp_sync_time()
{
    esp_sntp_config_t sntp_config = ESP_NETIF_SNTP_DEFAULT_CONFIG("pool.ntp.org");
    esp_netif_sntp_init(&sntp_config);

    /* POSIX timezones */
    setenv("TZ", "CST6CDT,M3.2.0,M11.1.0", 1); // CST
    tzset();

    if (esp_netif_sntp_sync_wait(pdMS_TO_TICKS(10000)) != ESP_OK)
    {
        ESP_LOGE("sntp", "Failed to synchronize time");
    } else {
        ESP_LOGI("sntp", "Time synchronized successfully");
    }
    UPDATE_TIME;
    sntp_set_nvs_time();
    char timeinfo_str[64];
    strftime(timeinfo_str, sizeof(timeinfo_str), "%Y-%m-%d %H:%M:%S", &timeinfo);
    ESP_LOGI("sntp", "Current time: %s", timeinfo_str);
    esp_netif_sntp_deinit();
}

static void IRAM_ATTR spi_write_byte(uint8_t byte)
{
    for (int i = 0; i < BITS_PER_BYTE; i++)
    {
        rtc_gpio_set_level(MOSI_PIN, (byte & 0x80) ? HIGH : LOW); // 0x80 = 10000000 BITMASK
        byte <<= 1;
        rtc_gpio_set_level(SCK_PIN, HIGH);
        rtc_gpio_set_level(SCK_PIN, LOW);
    }
    rtc_gpio_set_level(CS_PIN, HIGH);
}

static void IRAM_ATTR spi_write_command(uint8_t command)
{
    rtc_gpio_set_level(DC_PIN, LOW); // Command mode
    rtc_gpio_set_level(CS_PIN, LOW);
    spi_write_byte(command);
}

static void IRAM_ATTR spi_write_data(uint8_t data)
{
    rtc_gpio_set_level(DC_PIN, HIGH); // Data mode
    rtc_gpio_set_level(CS_PIN, LOW);
    spi_write_byte(data);
}

static void epd_reset()
{
    rtc_gpio_set_level(RST_PIN, HIGH);
    vTaskDelay(20 / portTICK_PERIOD_MS);
    rtc_gpio_set_level(RST_PIN, LOW); // Low is active
    vTaskDelay(20 / portTICK_PERIOD_MS);
    rtc_gpio_set_level(RST_PIN, HIGH);
}

static void epd_wait_until_idle()
{
    while (rtc_gpio_get_level(BUSY_PIN) == LOW)
    {
        ESP_LOGI("epd", "Display is busy...");
        vTaskDelay(10 / portTICK_PERIOD_MS);
    }
    ESP_LOGI("epd", "Display is released");
}

static void epd_init()
{
    /* Datasheet at https://files.waveshare.com/upload/6/60/7.5inch_e-Paper_V2_Specification.pdf
     * was used as a reference for the initialization sequence and commands */
    epd_reset();

    /* Default from datasheet unless otherwise specified */
    spi_write_command(BOOSTER_SOFT_START);
    spi_write_data(0x17);
    spi_write_data(0x17);
    spi_write_data(0x27);
    spi_write_data(0x17);

    spi_write_command(POWER_SETTING);
    spi_write_data(0x07);
    spi_write_data(0x17);
    spi_write_data(0x3f);
    spi_write_data(0x3f);

    spi_write_command(POWER_ON);
    epd_wait_until_idle();

    spi_write_command(PANEL_SETTING);
    spi_write_data(0x1f);

    spi_write_command(RESOLUTION_SETTING);
    spi_write_data(0x03);
    spi_write_data(0x20);
    spi_write_data(0x01);
    spi_write_data(0xe0);

    spi_write_command(DUAL_SPI);
    spi_write_data(0x00);

    spi_write_command(TCON_SETTING);
    spi_write_data(0x22);

    /* Altered from default to transfer data from NEW to OLD automatically */
    spi_write_command(VCOM_DATA_INTERVAL);
    spi_write_data(0x18);
    spi_write_data(0x07);

    /* Enable fast refresh */
    spi_write_command(CASCADE_SETTING);
    spi_write_data(0x02);
    spi_write_command(FORCE_TEMPERATURE);
    spi_write_data(0x5a);

    ESP_LOGI("epd", "Initialization complete");
}

static void epd_clear()
{
    epd_wait_until_idle();
    spi_write_command(TRANSFER_DATA_2);
    for (size_t i = 0; i < (EPD_HEIGHT * EPD_BYTE_WIDTH); i++)
    {
        spi_write_data(0x00);
    }
    spi_write_command(DISPLAY_REFRESH);
    epd_wait_until_idle();
}

static void epd_write_frame()
{
    epd_wait_until_idle();
    spi_write_command(TRANSFER_DATA_2);
    for (size_t i = 0; i < EPD_HEIGHT; i++)
    {
        for (size_t j = 0; j < EPD_BYTE_WIDTH; j++)
        {
            spi_write_data(frame[i][j]);
        }
    }
    spi_write_command(DISPLAY_REFRESH);
    epd_wait_until_idle();
}

// TODO: Draw an error message if an unrecoverable error occurs to inform user

static void epd_sleep()
{
    spi_write_command(POWER_OFF);
    epd_wait_until_idle();
}

static void IRAM_ATTR frame_draw_byte(int x, int y, uint8_t byte)
{
    if (x < 0 || x >= EPD_WIDTH || y < 0 || y >= EPD_HEIGHT)
    {
        ESP_LOGE("frame", "Byte position out of bounds: x=%d, y=%d", x, y);
        return;
    }
    /* Shift the byte to align with the correct bits in the frame buffer, then OR it with the existing byte
     * to preserve any pixels that have already been drawn in that byte. */
    frame[y][x / BITS_PER_BYTE] |= byte >> (x % BITS_PER_BYTE);
    /* If the byte being drawn isn't aligned to a byte boundary, then
     * the byte next to it also needs to be updated with the remaining bits. */
    if ((x % BITS_PER_BYTE) != 0 && (x / BITS_PER_BYTE + 1) < EPD_BYTE_WIDTH)
    {
        frame[y][x / BITS_PER_BYTE + 1] |= byte << (BITS_PER_BYTE - (x % BITS_PER_BYTE));
    }
}

static void frame_draw_char(font_t font, char c, int x, int y)
{
    uint8_t bytes_per_char = (font.width / BITS_PER_BYTE) + (font.width % BITS_PER_BYTE != 0);

    /* Subtract the first character in the font from the character to get the index,
     * then multiply by the number of bytes per character to get the offset in the font data array */
    size_t offset = (c - ' ') * font.height * bytes_per_char;
    const uint8_t *char_start = font.table + offset;

    /* Convert the 1D font data array for the character into a 2D array
     * for easier indexing when drawing to the frame buffer. */
    uint8_t char_2d[font.height][bytes_per_char];
    memcpy(char_2d, char_start, sizeof(char_2d));

    for (int i = 0; i < font.height; i++)
    {
        for (int j = 0; j < bytes_per_char; j++)
        {
            frame_draw_byte((x + (j * BITS_PER_BYTE)), (y + i), char_2d[i][j]);
        }
    }
}

static void frame_draw_giant_char(uint32_t offset, int x, int y)
{
    uint8_t bytes_per_char = (font60.width / BITS_PER_BYTE) + (font60.width % BITS_PER_BYTE != 0);
    const uint8_t *char_start = font60.table + offset;

    for (int i = 0; i < font60.height; i++)
    {
        for (int j = 0; j < bytes_per_char; j++)
        {
            frame_draw_byte((x + (j * BITS_PER_BYTE)), (y + i), char_start[i * bytes_per_char + j]);
        }
    }
}

static void frame_draw_string(font_t font, const char *str, int x, int y)
{
    while (str[0] != '\0')
    {
        /* Slightly cursed code to make periods look better */
        x -= (str[0] == '.' && font.width < 20) ? ((font.width / 2) - 1) : 0;
        frame_draw_char(font, *str, x, y);
        x += (str[0] != '.') ? font.width : ((font.width / 2) + 2);
        str++;
    }
}

static void frame_draw_image(const uint8_t *image_data, size_t length, int x, int y)
{
    int height = (length == 1545) ? 103 : 40,
        width = (length == 1545) ? 120 : 48;
    for (int i = 0; i < height; i++)
    {
        for (int j = 0; j < (width / BITS_PER_BYTE); j++)
        {
            uint8_t byte = image_data[i * (width / BITS_PER_BYTE) + j];
            frame_draw_byte(x + (j * BITS_PER_BYTE), y + i, byte);
        }
    }
}

/* Used to draw degree symbol, unecessary, but I wanted to implement the midpoint circle algorithm */
static void frame_draw_circle(int center_x, int center_y, int radius)
{
    /* Midpoint circle algorithm */
    int x = radius,
        y = 0,
        decision_over_2 = 1 - x; // Decision criterion divided by 2 evaluated at x=r, y=0

    while (y <= x)
    {
        frame_draw_byte(center_x + x, center_y + y, 0xc0);
        frame_draw_byte(center_x + y, center_y + x, 0xc0);
        frame_draw_byte(center_x - x, center_y + y, 0xc0);
        frame_draw_byte(center_x - y, center_y + x, 0xc0);
        frame_draw_byte(center_x - x, center_y - y, 0xc0);
        frame_draw_byte(center_x - y, center_y - x, 0xc0);
        frame_draw_byte(center_x + x, center_y - y, 0xc0);
        frame_draw_byte(center_x + y, center_y - x, 0xc0);
        y++;
        if (decision_over_2 <= 0) { decision_over_2 += 2 * y + 1; }
        else                      { x--; decision_over_2 += 2 * (y - x) + 1; }
    }
}

/* Bresenham's line algorithm, Used to draw arrows */
static void frame_draw_line(int x0, int y0, int x1, int y1)
{
    int dx = abs(x1 - x0),
        sx = (x0 < x1) ? 1 : -1,
        dy = -abs(y1 - y0),
        sy = (y0 < y1) ? 1 : -1,
        err = dx + dy,
        e2; // error value e_xy
    while (1)
    {
        frame_draw_byte(x0, y0, 0xc0);
        if (x0 == x1 && y0 == y1) break;
        e2 = 2 * err;
        if (e2 >= dy) { err += dy; x0 += sx; }
        if (e2 <= dx) { err += dx; y0 += sy; }
    }
}

/* Draws a rectangle with an x in the middle of it */
static void frame_draw_x_rectangle(int x0, int y0, int x1, int y1)
{
    for (int x = x0; x <= x1; x++)
    {
        frame_draw_byte(x, y0, 0x03);
        frame_draw_byte(x, y1, 0x03);
    }
    for (int y = y0; y <= y1; y++)
    {
        frame_draw_byte(x0, y, 0x03);
        frame_draw_byte(x1, y, 0x03);
    }
    frame_draw_line(x0, y0, x1, y1);
    frame_draw_line(x0, y1, x1, y0);
}

static void frame_draw_filled_triangle(int x0, int y0, int x1, int y1, int x2, int y2)
{
    frame_draw_line(x0, y0, x1, y1);
    frame_draw_line(x1, y1, x2, y2);
    frame_draw_line(x2, y2, x0, y0);

    int t;
    if (y0 > y1) { t=x0; x0=x1; x1=t; t=y0; y0=y1; y1=t; }
    if (y0 > y2) { t=x0; x0=x2; x2=t; t=y0; y0=y2; y2=t; }
    if (y1 > y2) { t=x1; x1=x2; x2=t; t=y1; y1=y2; y2=t; }
    int total_h = y2 - y0;

    for (int y = y0; y <= y2; y++)
    {
        int xa = (int)(x0 + (double)(x2 - x0) * (y - y0) / total_h);
        int xb;
        if (y <= y1)
        {
            int seg = y1 - y0;
            xb = (seg == 0) ? x0 : (int)(x0 + (double)(x1 - x0) * (y - y0) / seg);
        } else {
            int seg = y2 - y1;
            xb = (seg == 0) ? x1 : (int)(x1 + (double)(x2 - x1) * (y - y1) / seg);
        }
        if (xa > xb) { t = xa; xa = xb; xb = t; }

        int remaining = xb - xa + 1,
            x = xa;
        while (remaining > 0)
        {
            int bits = (remaining > 8) ? 8 : remaining;
            uint8_t mask = (uint8_t)(0xFF00u >> bits);
            frame_draw_byte(x, y, mask);
            x += bits;
            remaining -= bits;
        }
    }
}

static void frame_draw_compass(int x, int y, uint16_t degrees, int length)
{
    /* Convert degrees to radians and adjust so 0 degrees is pointing up */
    float radians = degrees * (M_PI / 180.0f);
    /* Draw a circle for the compass background */
    frame_draw_circle(x, y, length);
    /* Screen space unit vector in the direction of the wind */
    double dx      = sin(radians),
           dy      = -cos(radians),
    /* Perpendicular vector for the arrowhead */
           px      = dy,
           py      = -dx,
    /* Coordinates where the arrowhead is attached to the line */
           base_cx = x + 0.35 * length * dx,
           base_cy = y + 0.35 * length * dy;
    /* Second set of coordinates for the line of the arrow */
    int    edge_x  = (int)round(x + length * dx),
           edge_y  = (int)round(y + length * dy),
    /* Coordinates for the tip of the arrow */
           tip_x   = (int)round(x + 0.80 * length * dx),
           tip_y   = (int)round(y + 0.80 * length * dy),
    /* Coordinates for two sides of the triangle for the arrowhead, using the perpendicular vector */
           b1x     = (int)round(base_cx + 0.30 * length * px),
           b1y     = (int)round(base_cy + 0.30 * length * py),
           b2x     = (int)round(base_cx - 0.30 * length * px),
           b2y     = (int)round(base_cy - 0.30 * length * py);
    frame_draw_line(x, y, edge_x, edge_y);
    frame_draw_filled_triangle(tip_x, tip_y, b1x, b1y, b2x, b2y);

    /* Draw N, E, S, W indicators */
    frame_draw_char(font16, 'N', x - (font16.width / 2), y - length - font16.height);
    frame_draw_char(font16, 'E', x + length + 4, y - (font16.height / 2));
    frame_draw_char(font16, 'S', x - (font16.width / 2) + 2, y + length + 2);
    frame_draw_char(font16, 'W', x - length - font16.width - 2, y - (font16.height / 2));
}

static void frame_draw_time(uint16_t x, uint16_t y)
{
    UPDATE_TIME;
    uint16_t hour = timeinfo.tm_hour % 12,
             minute = timeinfo.tm_min,
             afternoon = (timeinfo.tm_hour >= 12) ? 0 : 1;
    hour = (hour == 0) ? 12 : hour; // Convert 0 to 12 for 12-hour format
    ESP_LOGI("time", "Current time: %02d:%02d %s", (hour == 0) ? 12 : hour, minute, afternoon ? "AM" : "PM");

    uint8_t time[] =
    {
        (hour / 10) % 10,
        hour % 10,
        10,
        (minute / 10) % 10,
        minute % 10,
        afternoon ? 11 : 12,
        13
    };

    for (int i = 0; i < sizeof(time); i++)
    {
        switch (time[i])
        {
            case 0:  frame_draw_giant_char(ZERO,     x + (i * font60.width), y); break;
            case 1:  frame_draw_giant_char(ONE,      x + (i * font60.width), y); break;
            case 2:  frame_draw_giant_char(TWO,      x + (i * font60.width), y); break;
            case 3:  frame_draw_giant_char(THREE,    x + (i * font60.width), y); break;
            case 4:  frame_draw_giant_char(FOUR,     x + (i * font60.width), y); break;
            case 5:  frame_draw_giant_char(FIVE,     x + (i * font60.width), y); break;
            case 6:  frame_draw_giant_char(SIX,      x + (i * font60.width), y); break;
            case 7:  frame_draw_giant_char(SEVEN,    x + (i * font60.width), y); break;
            case 8:  frame_draw_giant_char(EIGHT,    x + (i * font60.width), y); break;
            case 9:  frame_draw_giant_char(NINE,     x + (i * font60.width), y); break;
            case 10: frame_draw_giant_char(COLON,    x + (i * font60.width), y); break;
            case 11: frame_draw_giant_char(LETTER_A, x + (i * font60.width), y); break;
            case 12: frame_draw_giant_char(LETTER_P, x + (i * font60.width), y); break;
            case 13: frame_draw_giant_char(LETTER_M, x + (i * font60.width), y); break;
        }
    }
}

static void frame_draw_icon(int x, int y, uint16_t weather_id)
{
    /* Weather condition codes documented at https://openweathermap.org/weather-conditions */
    if (weather_id >= THUNDERSTORM_START && weather_id < DRIZZLE_START)
    {
        frame_draw_image(icon_thunder, sizeof(icon_thunder), x, y);
    }
    else if (weather_id >= DRIZZLE_START && weather_id < RAIN_START)
    {
        frame_draw_image(icon_drizzle, sizeof(icon_drizzle), x, y);
    }
    else if (weather_id >= RAIN_START && weather_id < SNOW_START)
    {
        frame_draw_image(icon_rain, sizeof(icon_rain), x, y);
    }
    else if (weather_id >= SNOW_START && weather_id < ATMOSPHERE_START)
    {
        frame_draw_image(icon_snow, sizeof(icon_snow), x, y);
    }
    else if (weather_id >= ATMOSPHERE_START && weather_id < CLEAR_SKY)
    {
        frame_draw_image(icon_haze, sizeof(icon_haze), x, y);
    }
    else if (weather_id == CLEAR_SKY)
    {
        frame_draw_image(icon_sun, sizeof(icon_sun), x, y);
    } else {
        frame_draw_image(icon_cloud, sizeof(icon_cloud), x, y);
    }
}

/* Draw graph of two sets of points with different y-axes, used for the temperature and precipitation forecast graph
 * first series of points is drawn with a solid line and the second series is drawn with as dashed boxes */
static void frame_draw_graph(int x1, int y1, int x2, int y2, float min_value, float max_value,
        const float *points, size_t num_points, int num_y_labels, const char *y_label_format,
        const float *points2, size_t num_points2, int num_y_labels2, const char *y_label_format2)
{
    /* Draw one base line for x axis and two base lines for the y axes */
    frame_draw_line(x1, y2, x2, y2);
    frame_draw_line(x1, y1, x1, y2);
    frame_draw_line(x2, y1, x2, y2);
    /* Draw labels for y axes */
    for (int i = 0; i < num_y_labels; i++)
    {
        float value = min_value + i * (max_value - min_value) / (num_y_labels - 1);
        char label[16];
        snprintf(label, sizeof(label), y_label_format, value);
        frame_draw_string(font16, label,
                x1 - (font16.width * strlen(label)) - 5,
                y2 - ((y2 - y1) * i / (num_y_labels - 1)) - (font16.height / 2));
    }
    for (int i = 0; i < num_y_labels2; i++)
    {
        float value = min_value + i * (max_value - min_value) / (num_y_labels2 - 1);
        char label[16];
        snprintf(label, sizeof(label), y_label_format2, value);
        frame_draw_string(font16, label,
                x2 + 5,
                y2 - ((y2 - y1) * i / (num_y_labels2 - 1)) - (font16.height / 2));
    }
    /* Draw points and lines for first series */
    for (size_t i = 0; i < num_points - 1; i++)
    {
        int x_start = x1 + (i * (x2 - x1) / (num_points - 1)),
            y_start = y2 - ((points[i] - min_value) * (y2 - y1) / (max_value - min_value)),
            x_end = x1 + ((i + 1) * (x2 - x1) / (num_points - 1)),
            y_end = y2 - ((points[i + 1] - min_value) * (y2 - y1) / (max_value - min_value));
        frame_draw_line(x_start, y_start, x_end, y_end);
    }
    /* Draw points for second series as dashed boxes */
    for (size_t i = 0; i < num_points2; i++)
    {
        int x_center = x1 + (i * (x2 - x1) / (num_points2 - 1)),
            y_center = y2 - ((points2[i] - min_value) * (y2 - y1) / (max_value - min_value));
        frame_draw_x_rectangle(x_center - 3, y_center - 3, x_center + 3, y_center + 3);
    }
}

static char *float_to_string(float value)
{
    static char buffer[16];
    if ((int)value == value)
    {
        snprintf(buffer, sizeof(buffer), "%d", (int)value); // Trim trailing .0 for whole numbers
    } else {
        snprintf(buffer, sizeof(buffer), "%.1f", value);
    }
    return buffer;
}

static uint16_t float_str_width(float value, uint16_t font_width)
{
    char *str = float_to_string(value);
    float str_width = strlen(str) * font_width;
    if (font_width <= 22)
    {
        str_width -= (strchr(str, '.') != NULL) ? font_width : 0;
    } else {
        str_width -= (strchr(str, '.') != NULL) ? (font_width / 2) : 0;
    }
    return str_width;
}

static void frame_draw_default()
{
    /* Quadrant 1: Current time and date */
    UPDATE_TIME;
    char timeinfo_str[64];
    frame_draw_string(font24, "It is ", 450, 20);
    strftime(timeinfo_str, sizeof(timeinfo_str), "%A,", &timeinfo);
    frame_draw_string(font24, timeinfo_str, (font24.width * strlen("It is ")) + 450, 20);
    strftime(timeinfo_str, sizeof(timeinfo_str), "%B %d, %Y", &timeinfo);
    frame_draw_string(font24, timeinfo_str, 470, 50);
    frame_draw_time(CLOCK_X, CLOCK_Y);

    /* Quadrant 2: Current weather conditions */
    frame_draw_icon(20, 20, weather.id);
    frame_draw_string(font20, "Currently, ", 10, 130);
    frame_draw_string(font40, float_to_string(weather.current_temp), 30, 160);
    frame_draw_circle((30 + float_str_width(weather.current_temp, font40.width)), 165, 5);
    frame_draw_string(font20, "feels like", 140, 180);
    frame_draw_string(font24, float_to_string(weather.feels_like_temp), 290, 176);
    frame_draw_circle((292 + float_str_width(weather.feels_like_temp, font24.width)), 176, 3);
    frame_draw_string(font24, "High: ", 175, 20);
    frame_draw_string(font24, float_to_string(weather.high_temp), 260, 20);
    frame_draw_circle((262 + float_str_width(weather.high_temp, font24.width)), 20, 3);
    frame_draw_string(font24, "Low: ", 175, 50);
    frame_draw_string(font24, float_to_string(weather.low_temp), 260, 50);
    frame_draw_circle((262 + float_str_width(weather.low_temp, font24.width)), 50, 3);
    frame_draw_string(font16, "Wind", 175, 80);
    frame_draw_string(font16, "Speed", 175, 95);
    frame_draw_image(icon_wind, sizeof(icon_wind), 235, 75);
    frame_draw_string(font24, float_to_string(weather.wind_speed), 285, 85);
    frame_draw_string(font16, "mph", (285 + float_str_width(weather.wind_speed, font24.width)), 90);
    frame_draw_compass(400, 100, weather.wind_direction_degrees, 15);
    frame_draw_string(font16, "Cloud", 175, 125);
    frame_draw_string(font16, "Cover", 175, 140);
    frame_draw_image(icon_cloud_small, sizeof(icon_cloud_small), 240, 120);
    frame_draw_string(font24, float_to_string(weather.cloudiness), 295, 130);
    frame_draw_string(font20, "%", (295 + float_str_width(weather.cloudiness, font24.width)), 125);

    /* TODO: Quadrant 3: Graph showing temperature and precipitaion chance */
    /*frame_draw_graph(20, 200, 470, 470, -10.0f, 110.0f,
            forecast_hourly_temps, sizeof(forecast_hourly_temps) / sizeof(forecast_hourly_temps[0]), 5, "%.0f°",
            forecast_hourly_precip_chances,
            sizeof(forecast_hourly_precip_chances) / sizeof(forecast_hourly_precip_chances[0]), 5, "%.0f%%"); */
    /* TODO: Quadrant 4: Forecast for next few days */
}

static void rtc_gpio_init_all()
{
    const gpio_num_t all_pins[] = {CS_PIN, DC_PIN, RST_PIN, BUSY_PIN, MOSI_PIN, SCK_PIN, PWR_PIN};
    for (size_t i = 0; i < sizeof(all_pins) / sizeof(all_pins[0]); i++)
    {
        assert(rtc_gpio_is_valid_gpio(all_pins[i]));
        gpio_reset_pin(all_pins[i]);
        rtc_gpio_init(all_pins[i]);
        if (all_pins[i] == BUSY_PIN)
        {
            rtc_gpio_set_direction(all_pins[i], RTC_GPIO_MODE_INPUT_ONLY);
        } else {
            rtc_gpio_set_direction(all_pins[i], RTC_GPIO_MODE_OUTPUT_ONLY);
        }
        rtc_gpio_pulldown_dis(all_pins[i]);
        rtc_gpio_pullup_dis(all_pins[i]);
        gpio_intr_disable(all_pins[i]);
    }
    rtc_gpio_set_level(PWR_PIN, HIGH);
    rtc_gpio_set_level(RST_PIN, HIGH);
}

static void rtc_gpio_set_low_all()
{
    rtc_gpio_set_level(CS_PIN, LOW);
    rtc_gpio_set_level(DC_PIN, LOW);
    rtc_gpio_set_level(RST_PIN, LOW);
    rtc_gpio_set_level(MOSI_PIN, LOW);
    rtc_gpio_set_level(SCK_PIN, LOW);
}

static void align_time_to_next_minute()
{
    UPDATE_TIME;
    int seconds_to_next_minute = 60 - timeinfo.tm_sec;
    ESP_LOGI("time",
            "Current time: %02d:%02d:%02d, sleeping for %d seconds to align to next minute",
            timeinfo.tm_hour, timeinfo.tm_min, timeinfo.tm_sec, seconds_to_next_minute);

    // TODO: This consumes alot of power, change to altering the ULP wakeup time
    vTaskDelay((seconds_to_next_minute * 1000) / portTICK_PERIOD_MS);

    UPDATE_TIME;
    ulp_hours = timeinfo.tm_hour % 12;
    ulp_hours = (ulp_hours == 0) ? 12 : ulp_hours;
    ulp_minutes = timeinfo.tm_min;
}

static void test_weather_data()
{
    weather.id = 200;
    weather.current_temp = 72.8f;
    weather.feels_like_temp = 75.0f;
    weather.high_temp = 80.0f;
    weather.low_temp = 65.0f;
    weather.wind_speed = 15.0f;
    weather.wind_direction_degrees = 215; // Southeast
    weather.cloudiness = 75.0f;
}

static void task_wifi_start(void *pvParameters)
{
    wifi_if = wifi_start();
    xEventGroupSetBits(event_group, WIFI_DONE_BIT);
    ESP_LOGI("wifi", "Wi-Fi task complete, bit set");
    vTaskDelete(NULL);
}

static void task_sntp_sync_time(void *pvParameters)
{
    ESP_LOGI("sntp", "Waiting for Wi-Fi to be connected...");
    xEventGroupWaitBits(event_group, WIFI_DONE_BIT, pdFALSE, pdTRUE, portMAX_DELAY);
    sntp_sync_time();
    xEventGroupSetBits(event_group, SNTP_DONE_BIT);
    ESP_LOGI("sntp", "SNTP sync task complete, bit set");
    vTaskDelete(NULL);
}

static void task_https_get_weather(void *pvParameters)
{
    ESP_LOGI("weather", "Waiting for Wi-Fi to be connected...");
    xEventGroupWaitBits(event_group, WIFI_DONE_BIT, pdFALSE, pdTRUE, portMAX_DELAY);
    if (sntp_get_nvs_time())
    {
        ESP_LOGI("weather", "Time obtained from NVS, not waiting for SNTP sync");
    } else {
        ESP_LOGI("weather", "No time in NVS, waiting for SNTP sync to complete...");
        xEventGroupWaitBits(event_group, SNTP_DONE_BIT, pdFALSE, pdTRUE, portMAX_DELAY);
    }
    ESP_LOGI("weather", "Finished waiting for dependencies, starting weather data retrieval");
    https_get_weather();
    xEventGroupSetBits(event_group, WEATHER_DONE_BIT);
    ESP_LOGI("weather", "Weather data retrieval complete");
    vTaskDelete(NULL);
}

void app_main()
{
    vTaskDelay(2000 / portTICK_PERIOD_MS); // Delay for serial monitor
    /* Default log level is set to ERROR to speed up boot time, set it back to INFO */
    esp_log_level_set("*", ESP_LOG_INFO);

    /* Wi-Fi requires NVS flash to store credentials otherwise it will fail to initialize */
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND)
    {
        /* If these fail they probably can't be recovered from */
        ESP_ERROR_CHECK(nvs_flash_erase());
        ESP_ERROR_CHECK(nvs_flash_init());
    }

    /* Init ULP so its variables can be accessed and modified from the main CPU */
    esp_sleep_source_t wakeup_reason = esp_sleep_get_wakeup_cause();
    if (wakeup_reason == ESP_SLEEP_WAKEUP_UNDEFINED)
    {
        rtc_gpio_init_all();
        ESP_ERROR_CHECK_WITHOUT_ABORT(ulp_riscv_load_binary(bin_start, (bin_end - bin_start)));
        ulp_set_wakeup_period(0, 10);
        ESP_ERROR_CHECK_WITHOUT_ABORT(ulp_riscv_run()); // Exits immediately after starting
        esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON); // Keep GPIO pins enabled in deep sleep
        esp_sleep_pd_config(ESP_PD_DOMAIN_RC_FAST, ESP_PD_OPTION_ON); // Keep RTC fast clock on for ULP
        ulp_clk_cal = rtc_clk_cal(RTC_CAL_RTC_MUX, 1000); // Calibrate RTC clock against main one
    }

    event_group = xEventGroupCreate();
    if (event_group == NULL)
    {
        ESP_LOGE("main", "Failed to create event group");
        return;
    }
    xTaskCreate(task_wifi_start, "wifi_start", 4096, NULL, 5, NULL);
    xTaskCreate(task_sntp_sync_time, "sntp_sync_time", 4096, NULL, 5, NULL);
    xTaskCreate(task_https_get_weather, "https_get_weather", 65536, NULL, 5, NULL);

    xEventGroupWaitBits(event_group, ALL_DONE_BITS, pdFALSE, pdTRUE, portMAX_DELAY);
    wifi_stop(wifi_if);
    vEventGroupDelete(event_group);
    ESP_LOGI("main", "All tasks complete, proceeding to draw frame and enter deep sleep");

    epd_init();
    frame_draw_default();
    epd_write_frame();
    epd_sleep();
    rtc_gpio_set_low_all();

    align_time_to_next_minute();
    ulp_set_wakeup_period(0, (60ULL * 1000ULL * 1000ULL)); // 60 seconds in uS
    ulp_riscv_timer_resume();
    esp_sleep_enable_timer_wakeup(179ULL * 60ULL * 1000ULL * 1000ULL); // 3 hours in uS
    esp_deep_sleep_start();
}
